//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractItemAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractItemAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractItemAction")
@XmlSeeAlso({
    EnchantItemAction.class,
    ToyPetSpawnAction.class,
    DecorateAction.class,
    FireworksUseAction.class,
    CraftLearnAction.class,
    ExpandInventoryAction.class,
    RideAction.class,
    AssemblyItemAction.class,
    EmotionLearnAction.class,
    DyeAction.class,
    CosmeticItemAction.class,
    SkillLearnAction.class,
    QuestStartAction.class,
    SkillUseAction.class,
    ToyPetAdoptAction.class,
    ChargeAction.class,
    ReadAction.class,
    AnimationAddAction.class,
    TitleAddAction.class,
    DecomposeAction.class,
    SummonHouseObjectAction.class,
    ExtractAction.class
})
public abstract class AbstractItemAction {


}
