//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Acquisition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Acquisition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ap" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="item" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="type" type="{}acquisitionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Acquisition")
public class Acquisition {

    @XmlAttribute
    protected Integer ap;
    @XmlAttribute
    protected Integer count;
    @XmlAttribute
    protected Integer item;
    @XmlAttribute
    protected AcquisitionType type;

    /**
     * Gets the value of the ap property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getAp() {
        if (ap == null) {
            return  0;
        } else {
            return ap;
        }
    }

    /**
     * Sets the value of the ap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAp(Integer value) {
        this.ap = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCount() {
        if (count == null) {
            return  0;
        } else {
            return count;
        }
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCount(Integer value) {
        this.count = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getItem() {
        if (item == null) {
            return  0;
        } else {
            return item;
        }
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setItem(Integer value) {
        this.item = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AcquisitionType }
     *     
     */
    public AcquisitionType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcquisitionType }
     *     
     */
    public void setType(AcquisitionType value) {
        this.type = value;
    }

}
