//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Actions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Actions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="itemuse" type="{}ItemUseAction" minOccurs="0"/>
 *         &lt;element name="mpuse" type="{}MpUseAction" minOccurs="0"/>
 *         &lt;element name="hpuse" type="{}HpUseAction" minOccurs="0"/>
 *         &lt;element name="dpuse" type="{}DpUseAction" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Actions", propOrder = {
    "itemuseAndMpuseAndHpuse"
})
public class Actions {

    @XmlElements({
        @XmlElement(name = "itemuse", type = ItemUseAction.class),
        @XmlElement(name = "hpuse", type = HpUseAction.class),
        @XmlElement(name = "dpuse", type = DpUseAction.class),
        @XmlElement(name = "mpuse", type = MpUseAction.class)
    })
    protected List<Action> itemuseAndMpuseAndHpuse;

    /**
     * Gets the value of the itemuseAndMpuseAndHpuse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemuseAndMpuseAndHpuse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemuseAndMpuseAndHpuse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemUseAction }
     * {@link HpUseAction }
     * {@link DpUseAction }
     * {@link MpUseAction }
     * 
     * 
     */
    public List<Action> getItemuseAndMpuseAndHpuse() {
        if (itemuseAndMpuseAndHpuse == null) {
            itemuseAndMpuseAndHpuse = new ArrayList<Action>();
        }
        return this.itemuseAndMpuseAndHpuse;
    }

}
