//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionModifiers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionModifiers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="backdamage" type="{}BackDamageModifier" minOccurs="0"/>
 *         &lt;element name="frontdamage" type="{}FrontDamageModifier" minOccurs="0"/>
 *         &lt;element name="abnormaldamage" type="{}AbnormalDamageModifier" minOccurs="0"/>
 *         &lt;element name="targetrace" type="{}TargetRaceDamageModifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionModifiers", propOrder = {
    "backdamageAndFrontdamageAndAbnormaldamage"
})
public class ActionModifiers {

    @XmlElements({
        @XmlElement(name = "backdamage", type = BackDamageModifier.class),
        @XmlElement(name = "abnormaldamage", type = AbnormalDamageModifier.class),
        @XmlElement(name = "targetrace", type = TargetRaceDamageModifier.class),
        @XmlElement(name = "frontdamage", type = FrontDamageModifier.class)
    })
    protected List<ActionModifier> backdamageAndFrontdamageAndAbnormaldamage;

    /**
     * Gets the value of the backdamageAndFrontdamageAndAbnormaldamage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the backdamageAndFrontdamageAndAbnormaldamage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBackdamageAndFrontdamageAndAbnormaldamage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BackDamageModifier }
     * {@link AbnormalDamageModifier }
     * {@link TargetRaceDamageModifier }
     * {@link FrontDamageModifier }
     * 
     * 
     */
    public List<ActionModifier> getBackdamageAndFrontdamageAndAbnormaldamage() {
        if (backdamageAndFrontdamageAndAbnormaldamage == null) {
            backdamageAndFrontdamageAndAbnormaldamage = new ArrayList<ActionModifier>();
        }
        return this.backdamageAndFrontdamageAndAbnormaldamage;
    }

}
