//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuraEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuraEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}Effect">
 *       &lt;attribute name="distance_z" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="distance" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="skill_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuraEffect")
public class AuraEffect
    extends Effect
{

    @XmlAttribute(name = "distance_z")
    protected Integer distanceZ;
    @XmlAttribute
    protected Integer distance;
    @XmlAttribute(name = "skill_id")
    protected Integer skillId;

    /**
     * Gets the value of the distanceZ property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDistanceZ() {
        return distanceZ;
    }

    /**
     * Sets the value of the distanceZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDistanceZ(Integer value) {
        this.distanceZ = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDistance(Integer value) {
        this.distance = value;
    }

    /**
     * Gets the value of the skillId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSkillId() {
        return skillId;
    }

    /**
     * Sets the value of the skillId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSkillId(Integer value) {
        this.skillId = value;
    }

}
