//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BufEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BufEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}Effect">
 *       &lt;attribute name="maxstat" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BufEffect")
@XmlSeeAlso({
    WeaponStatupEffect.class,
    ShieldMasteryEffect.class,
    OneTimeBoostHealEffect.class,
    SubTypeExtendDurationEffect.class,
    ExtendAuraRangeEffect.class,
    NoDeathPenaltyEffect.class,
    StatboostEffect.class,
    HiPassEffect.class,
    OneTimeBoostSkillCriticalEffect.class,
    BoostSpellAttackEffect.class,
    CurseEffect.class,
    DeboostHealEffect.class,
    XPBoostEffect.class,
    NoResurrectPenaltyEffect.class,
    BoostSkillCastingTimeEffect.class,
    BoostDropRateEffect.class,
    WeaponMasteryEffect.class,
    WeaponStatboostEffect.class,
    ArmorMasteryEffect.class,
    StatupEffect.class,
    StatdownEffect.class,
    SwitchHostileEffect.class,
    BoostHateEffect.class,
    SubTypeBoostResistEffect.class,
    BoostHealEffect.class,
    WeaponDualEffect.class
})
public abstract class BufEffect
    extends Effect
{

    @XmlAttribute
    protected Boolean maxstat;

    /**
     * Gets the value of the maxstat property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getMaxstat() {
        return maxstat;
    }

    /**
     * Sets the value of the maxstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMaxstat(Boolean value) {
        this.maxstat = value;
    }

}
