//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CarveSignetEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarveSignetEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}DamageEffect">
 *       &lt;attribute name="prob" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="signetlvlstart" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="signetlvl" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="signetid" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="signet" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarveSignetEffect")
public class CarveSignetEffect
    extends DamageEffect
{

    @XmlAttribute
    protected Integer prob;
    @XmlAttribute
    protected Integer signetlvlstart;
    @XmlAttribute(required = true)
    protected int signetlvl;
    @XmlAttribute(required = true)
    protected int signetid;
    @XmlAttribute(required = true)
    protected String signet;

    /**
     * Gets the value of the prob property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProb() {
        return prob;
    }

    /**
     * Sets the value of the prob property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProb(Integer value) {
        this.prob = value;
    }

    /**
     * Gets the value of the signetlvlstart property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSignetlvlstart() {
        return signetlvlstart;
    }

    /**
     * Sets the value of the signetlvlstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSignetlvlstart(Integer value) {
        this.signetlvlstart = value;
    }

    /**
     * Gets the value of the signetlvl property.
     * 
     */
    public int getSignetlvl() {
        return signetlvl;
    }

    /**
     * Sets the value of the signetlvl property.
     * 
     */
    public void setSignetlvl(int value) {
        this.signetlvl = value;
    }

    /**
     * Gets the value of the signetid property.
     * 
     */
    public int getSignetid() {
        return signetid;
    }

    /**
     * Sets the value of the signetid property.
     * 
     */
    public void setSignetid(int value) {
        this.signetid = value;
    }

    /**
     * Gets the value of the signet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignet() {
        return signet;
    }

    /**
     * Sets the value of the signet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignet(String value) {
        this.signet = value;
    }

}
