//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CaseHealEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseHealEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractHealEffect">
 *       &lt;attribute name="cond_value" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="type" type="{}HealType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseHealEffect")
public class CaseHealEffect
    extends AbstractHealEffect
{

    @XmlAttribute(name = "cond_value")
    protected Integer condValue;
    @XmlAttribute
    protected HealType type;

    /**
     * Gets the value of the condValue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCondValue() {
        return condValue;
    }

    /**
     * Sets the value of the condValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCondValue(Integer value) {
        this.condValue = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link HealType }
     *     
     */
    public HealType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealType }
     *     
     */
    public void setType(HealType value) {
        this.type = value;
    }

}
