//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Category.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Category">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="ARROW"/>
 *     &lt;enumeration value="WINGS"/>
 *     &lt;enumeration value="WINGS_BONE"/>
 *     &lt;enumeration value="MANASTONE"/>
 *     &lt;enumeration value="MANASTONE_SACK"/>
 *     &lt;enumeration value="MANASTONE_ENCHANTMENT_BOX"/>
 *     &lt;enumeration value="GODSTONE"/>
 *     &lt;enumeration value="GODSTONE_SACK"/>
 *     &lt;enumeration value="ENCHANTMENT"/>
 *     &lt;enumeration value="ENCHANTMENT_POUCH"/>
 *     &lt;enumeration value="FLUX"/>
 *     &lt;enumeration value="FLUX_POUCH"/>
 *     &lt;enumeration value="FLUX_BOX"/>
 *     &lt;enumeration value="BALIC_EMOTION"/>
 *     &lt;enumeration value="BALIC_EMOTION_SACK"/>
 *     &lt;enumeration value="BALIC_MATERIAL"/>
 *     &lt;enumeration value="BALIC_MATERIAL_POUCH"/>
 *     &lt;enumeration value="BALIC_MATERIAL_SACK"/>
 *     &lt;enumeration value="BALIC_HEART"/>
 *     &lt;enumeration value="RAWHIDE"/>
 *     &lt;enumeration value="SOULSTONE"/>
 *     &lt;enumeration value="SOULSTONE_POUCH"/>
 *     &lt;enumeration value="RECIPE"/>
 *     &lt;enumeration value="GATHERABLE"/>
 *     &lt;enumeration value="CRAFT_BOOST"/>
 *     &lt;enumeration value="SWORD"/>
 *     &lt;enumeration value="DAGGER"/>
 *     &lt;enumeration value="MACE"/>
 *     &lt;enumeration value="ORB"/>
 *     &lt;enumeration value="SPELLBOOK"/>
 *     &lt;enumeration value="GREATSWORD"/>
 *     &lt;enumeration value="POLEARM"/>
 *     &lt;enumeration value="STAFF"/>
 *     &lt;enumeration value="BOW"/>
 *     &lt;enumeration value="GUN"/>
 *     &lt;enumeration value="CANON"/>
 *     &lt;enumeration value="HARP"/>
 *     &lt;enumeration value="KEYBLADE"/>
 *     &lt;enumeration value="KEYHAMMER"/>
 *     &lt;enumeration value="TOOLHOE"/>
 *     &lt;enumeration value="TOOLPICK"/>
 *     &lt;enumeration value="TOOLROD"/>
 *     &lt;enumeration value="SHIELD"/>
 *     &lt;enumeration value="JACKET"/>
 *     &lt;enumeration value="PANTS"/>
 *     &lt;enumeration value="SHOES"/>
 *     &lt;enumeration value="GLOVES"/>
 *     &lt;enumeration value="SHOULDERS"/>
 *     &lt;enumeration value="NECKLACE"/>
 *     &lt;enumeration value="EARRINGS"/>
 *     &lt;enumeration value="RINGS"/>
 *     &lt;enumeration value="HELMET"/>
 *     &lt;enumeration value="BELT"/>
 *     &lt;enumeration value="SKILLBOOK"/>
 *     &lt;enumeration value="STIGMA"/>
 *     &lt;enumeration value="STIGMA_ADVANCED"/>
 *     &lt;enumeration value="STIGMA_SHARDS"/>
 *     &lt;enumeration value="POWER_SHARDS"/>
 *     &lt;enumeration value="POWER_SHARDS_SACK"/>
 *     &lt;enumeration value="COIN"/>
 *     &lt;enumeration value="COIN_BOX"/>
 *     &lt;enumeration value="MEDAL"/>
 *     &lt;enumeration value="MEDAL_BOX"/>
 *     &lt;enumeration value="QUEST_ITEM"/>
 *     &lt;enumeration value="QUEST_START_ITEM"/>
 *     &lt;enumeration value="QUEST_USE_ITEM"/>
 *     &lt;enumeration value="FIRECRACKER"/>
 *     &lt;enumeration value="EXTRACTOR"/>
 *     &lt;enumeration value="DYE"/>
 *     &lt;enumeration value="DYE_REMOVER"/>
 *     &lt;enumeration value="PAINT"/>
 *     &lt;enumeration value="PAINT_REMOVER"/>
 *     &lt;enumeration value="KEY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Category")
@XmlEnum
public enum Category {

    NONE,
    ARROW,
    WINGS,
    WINGS_BONE,
    MANASTONE,
    MANASTONE_SACK,
    MANASTONE_ENCHANTMENT_BOX,
    GODSTONE,
    GODSTONE_SACK,
    ENCHANTMENT,
    ENCHANTMENT_POUCH,
    FLUX,
    FLUX_POUCH,
    FLUX_BOX,
    BALIC_EMOTION,
    BALIC_EMOTION_SACK,
    BALIC_MATERIAL,
    BALIC_MATERIAL_POUCH,
    BALIC_MATERIAL_SACK,
    BALIC_HEART,
    RAWHIDE,
    SOULSTONE,
    SOULSTONE_POUCH,
    RECIPE,
    GATHERABLE,
    CRAFT_BOOST,
    SWORD,
    DAGGER,
    MACE,
    ORB,
    SPELLBOOK,
    GREATSWORD,
    POLEARM,
    STAFF,
    BOW,
    GUN,
    CANON,
    HARP,
    KEYBLADE,
    KEYHAMMER,
    TOOLHOE,
    TOOLPICK,
    TOOLROD,
    SHIELD,
    JACKET,
    PANTS,
    SHOES,
    GLOVES,
    SHOULDERS,
    NECKLACE,
    EARRINGS,
    RINGS,
    HELMET,
    BELT,
    SKILLBOOK,
    STIGMA,
    STIGMA_ADVANCED,
    STIGMA_SHARDS,
    POWER_SHARDS,
    POWER_SHARDS_SACK,
    COIN,
    COIN_BOX,
    MEDAL,
    MEDAL_BOX,
    QUEST_ITEM,
    QUEST_START_ITEM,
    QUEST_USE_ITEM,
    FIRECRACKER,
    EXTRACTOR,
    DYE,
    DYE_REMOVER,
    PAINT,
    PAINT_REMOVER,
    KEY;

    public String value() {
        return name();
    }

    public static Category fromValue(String v) {
        return valueOf(v);
    }

}
