//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChainCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChainCondition">
 *   &lt;complexContent>
 *     &lt;extension base="{}Condition">
 *       &lt;attribute name="selfcount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="precount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="precategory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="category" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChainCondition")
public class ChainCondition
    extends Condition
{

    @XmlAttribute
    protected Integer selfcount;
    @XmlAttribute
    protected Integer precount;
    @XmlAttribute
    protected Integer time;
    @XmlAttribute
    protected String precategory;
    @XmlAttribute
    protected String category;

    /**
     * Gets the value of the selfcount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSelfcount() {
        return selfcount;
    }

    /**
     * Sets the value of the selfcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSelfcount(Integer value) {
        this.selfcount = value;
    }

    /**
     * Gets the value of the precount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrecount() {
        return precount;
    }

    /**
     * Sets the value of the precount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrecount(Integer value) {
        this.precount = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTime(Integer value) {
        this.time = value;
    }

    /**
     * Gets the value of the precategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecategory() {
        return precategory;
    }

    /**
     * Sets the value of the precategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecategory(String value) {
        this.precategory = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

}
