//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Condition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Condition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Condition")
@XmlSeeAlso({
    DpCondition.class,
    PlayerMovedCondition.class,
    ArmorCondition.class,
    ArrowCheckCondition.class,
    SelfFlyingCondition.class,
    ChainCondition.class,
    MpCondition.class,
    OnFlyCondition.class,
    NoFlyingCondition.class,
    WeaponCondition.class,
    BackCondition.class,
    TargetFlyingCondition.class,
    ChargeCondition.class,
    AbnormalStateCondition.class,
    FormCondition.class,
    TargetCondition.class,
    CombatCheckCondition.class,
    HpCondition.class
})
public abstract class Condition {


}
