//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Conditions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Conditions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="mp" type="{}MpCondition" minOccurs="0"/>
 *         &lt;element name="hp" type="{}HpCondition" minOccurs="0"/>
 *         &lt;element name="dp" type="{}DpCondition" minOccurs="0"/>
 *         &lt;element name="target" type="{}TargetCondition" minOccurs="0"/>
 *         &lt;element name="playermove" type="{}PlayerMovedCondition" minOccurs="0"/>
 *         &lt;element name="arrowcheck" type="{}ArrowCheckCondition" minOccurs="0"/>
 *         &lt;element name="abnormal" type="{}AbnormalStateCondition" minOccurs="0"/>
 *         &lt;element name="onfly" type="{}OnFlyCondition" minOccurs="0"/>
 *         &lt;element name="noflying" type="{}NoFlyingCondition" minOccurs="0"/>
 *         &lt;element name="weapon" type="{}WeaponCondition" minOccurs="0"/>
 *         &lt;element name="armor" type="{}ArmorCondition" minOccurs="0"/>
 *         &lt;element name="charge" type="{}ChargeCondition" minOccurs="0"/>
 *         &lt;element name="targetflying" type="{}TargetFlyingCondition" minOccurs="0"/>
 *         &lt;element name="selfflying" type="{}SelfFlyingCondition" minOccurs="0"/>
 *         &lt;element name="combatcheck" type="{}CombatCheckCondition" minOccurs="0"/>
 *         &lt;element name="chain" type="{}ChainCondition" minOccurs="0"/>
 *         &lt;element name="back" type="{}BackCondition" minOccurs="0"/>
 *         &lt;element name="form" type="{}FormCondition" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Conditions", propOrder = {
    "mpAndHpAndDp"
})
public class Conditions {

    @XmlElements({
        @XmlElement(name = "selfflying", type = SelfFlyingCondition.class),
        @XmlElement(name = "charge", type = ChargeCondition.class),
        @XmlElement(name = "onfly", type = OnFlyCondition.class),
        @XmlElement(name = "back", type = BackCondition.class),
        @XmlElement(name = "dp", type = DpCondition.class),
        @XmlElement(name = "combatcheck", type = CombatCheckCondition.class),
        @XmlElement(name = "arrowcheck", type = ArrowCheckCondition.class),
        @XmlElement(name = "target", type = TargetCondition.class),
        @XmlElement(name = "chain", type = ChainCondition.class),
        @XmlElement(name = "abnormal", type = AbnormalStateCondition.class),
        @XmlElement(name = "targetflying", type = TargetFlyingCondition.class),
        @XmlElement(name = "mp", type = MpCondition.class),
        @XmlElement(name = "armor", type = ArmorCondition.class),
        @XmlElement(name = "playermove", type = PlayerMovedCondition.class),
        @XmlElement(name = "hp", type = HpCondition.class),
        @XmlElement(name = "weapon", type = WeaponCondition.class),
        @XmlElement(name = "form", type = FormCondition.class),
        @XmlElement(name = "noflying", type = NoFlyingCondition.class)
    })
    protected List<Condition> mpAndHpAndDp;

    /**
     * Gets the value of the mpAndHpAndDp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mpAndHpAndDp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMpAndHpAndDp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelfFlyingCondition }
     * {@link ChargeCondition }
     * {@link OnFlyCondition }
     * {@link BackCondition }
     * {@link DpCondition }
     * {@link CombatCheckCondition }
     * {@link ArrowCheckCondition }
     * {@link TargetCondition }
     * {@link ChainCondition }
     * {@link AbnormalStateCondition }
     * {@link TargetFlyingCondition }
     * {@link MpCondition }
     * {@link ArmorCondition }
     * {@link PlayerMovedCondition }
     * {@link HpCondition }
     * {@link WeaponCondition }
     * {@link FormCondition }
     * {@link NoFlyingCondition }
     * 
     * 
     */
    public List<Condition> getMpAndHpAndDp() {
        if (mpAndHpAndDp == null) {
            mpAndHpAndDp = new ArrayList<Condition>();
        }
        return this.mpAndHpAndDp;
    }

}
