//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreatureVisualState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CreatureVisualState">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HIDE1"/>
 *     &lt;enumeration value="HIDE2"/>
 *     &lt;enumeration value="HIDE3"/>
 *     &lt;enumeration value="HIDE5"/>
 *     &lt;enumeration value="HIDE10"/>
 *     &lt;enumeration value="HIDE13"/>
 *     &lt;enumeration value="HIDE20"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CreatureVisualState")
@XmlEnum
public enum CreatureVisualState {

    @XmlEnumValue("HIDE1")
    HIDE_1("HIDE1"),
    @XmlEnumValue("HIDE2")
    HIDE_2("HIDE2"),
    @XmlEnumValue("HIDE3")
    HIDE_3("HIDE3"),
    @XmlEnumValue("HIDE5")
    HIDE_5("HIDE5"),
    @XmlEnumValue("HIDE10")
    HIDE_10("HIDE10"),
    @XmlEnumValue("HIDE13")
    HIDE_13("HIDE13"),
    @XmlEnumValue("HIDE20")
    HIDE_20("HIDE20");
    private final String value;

    CreatureVisualState(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CreatureVisualState fromValue(String v) {
        for (CreatureVisualState c: CreatureVisualState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
