//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreatureSeeState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CreatureSeeState">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SEARCH1"/>
 *     &lt;enumeration value="SEARCH2"/>
 *     &lt;enumeration value="SEARCH5"/>
 *     &lt;enumeration value="SEARCH10"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CreatureSeeState")
@XmlEnum
public enum CreatureSeeState {

    @XmlEnumValue("SEARCH1")
    SEARCH_1("SEARCH1"),
    @XmlEnumValue("SEARCH2")
    SEARCH_2("SEARCH2"),
    @XmlEnumValue("SEARCH5")
    SEARCH_5("SEARCH5"),
    @XmlEnumValue("SEARCH10")
    SEARCH_10("SEARCH10");
    private final String value;

    CreatureSeeState(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CreatureSeeState fromValue(String v) {
        for (CreatureSeeState c: CreatureSeeState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
