//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DamageEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DamageEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}Effect">
 *       &lt;attribute name="mode" type="{}StatFunc" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DamageEffect")
@XmlSeeAlso({
    MpAttackInstantEffect.class,
    MoveBehindEffect.class,
    DeathBlowEffect.class,
    DispelBuffCounterAtkEffect.class,
    SpellAtkDrainInstantEffect.class,
    DelayedSpellAttackInstantEffect.class,
    DashEffect.class,
    FpAttackInstantEffect.class,
    ProcAtkInstantEffect.class,
    NoReduceSpellATKInstantEffect.class,
    CarveSignetEffect.class,
    SignetBurstEffect.class,
    BackDashEffect.class,
    SkillAttackInstantEffect.class,
    SkillAtkDrainInstantEffect.class,
    SpellAttackInstantEffect.class
})
public abstract class DamageEffect
    extends Effect
{

    @XmlAttribute
    protected StatFunc mode;

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link StatFunc }
     *     
     */
    public StatFunc getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatFunc }
     *     
     */
    public void setMode(StatFunc value) {
        this.mode = value;
    }

}
