//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DispelEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispelEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}Effect">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="effectids" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="effecttype" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="slottype" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dispeltype" type="{}DispelType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispelEffect", propOrder = {
    "effectids",
    "effecttype",
    "slottype"
})
@XmlSeeAlso({
    EvadeEffect.class
})
public class DispelEffect
    extends Effect
{

    @XmlElement(type = Integer.class)
    protected List<Integer> effectids;
    protected List<String> effecttype;
    protected List<String> slottype;
    @XmlAttribute
    protected DispelType dispeltype;

    /**
     * Gets the value of the effectids property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the effectids property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffectids().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getEffectids() {
        if (effectids == null) {
            effectids = new ArrayList<Integer>();
        }
        return this.effectids;
    }

    /**
     * Gets the value of the effecttype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the effecttype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffecttype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEffecttype() {
        if (effecttype == null) {
            effecttype = new ArrayList<String>();
        }
        return this.effecttype;
    }

    /**
     * Gets the value of the slottype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the slottype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSlottype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSlottype() {
        if (slottype == null) {
            slottype = new ArrayList<String>();
        }
        return this.slottype;
    }

    /**
     * Gets the value of the dispeltype property.
     * 
     * @return
     *     possible object is
     *     {@link DispelType }
     *     
     */
    public DispelType getDispeltype() {
        return dispeltype;
    }

    /**
     * Sets the value of the dispeltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispelType }
     *     
     */
    public void setDispeltype(DispelType value) {
        this.dispeltype = value;
    }

}
