//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DispelBuffCounterAtkEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispelBuffCounterAtkEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}DamageEffect">
 *       &lt;attribute name="dpower" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="power" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="dispel_level" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="hitdelta" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="hitvalue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispelBuffCounterAtkEffect")
public class DispelBuffCounterAtkEffect
    extends DamageEffect
{

    @XmlAttribute
    protected Integer dpower;
    @XmlAttribute
    protected Integer power;
    @XmlAttribute(name = "dispel_level")
    protected Integer dispelLevel;
    @XmlAttribute
    protected Integer hitdelta;
    @XmlAttribute
    protected Integer hitvalue;

    /**
     * Gets the value of the dpower property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDpower() {
        return dpower;
    }

    /**
     * Sets the value of the dpower property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDpower(Integer value) {
        this.dpower = value;
    }

    /**
     * Gets the value of the power property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPower(Integer value) {
        this.power = value;
    }

    /**
     * Gets the value of the dispelLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDispelLevel() {
        return dispelLevel;
    }

    /**
     * Sets the value of the dispelLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDispelLevel(Integer value) {
        this.dispelLevel = value;
    }

    /**
     * Gets the value of the hitdelta property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHitdelta() {
        return hitdelta;
    }

    /**
     * Sets the value of the hitdelta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHitdelta(Integer value) {
        this.hitdelta = value;
    }

    /**
     * Gets the value of the hitvalue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHitvalue() {
        return hitvalue;
    }

    /**
     * Sets the value of the hitvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHitvalue(Integer value) {
        this.hitvalue = value;
    }

}
