//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Effect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Effect">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subeffect" type="{}SubEffect" minOccurs="0"/>
 *         &lt;element name="modifiers" type="{}ActionModifiers" minOccurs="0"/>
 *         &lt;element name="change" type="{}Change" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="conditions" type="{}Conditions" minOccurs="0"/>
 *         &lt;element name="subconditions" type="{}Conditions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="hopa" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="hopb" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="hoptype" type="{}HopType" />
 *       &lt;attribute name="critadddmg1" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="critadddmg2" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="critprobmod2" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="preeffect_prob" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="preeffect" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="element" type="{}SkillElement" />
 *       &lt;attribute name="hittypeprob2" type="{http://www.w3.org/2001/XMLSchema}int" default="100" />
 *       &lt;attribute name="hittype" type="{}HitType" default="EVERYHIT" />
 *       &lt;attribute name="mrresist" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="accmod1" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="accmod2" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="noresist" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="basiclvl" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="e" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="effectid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="randomtime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="duration1" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="duration2" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="onfly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="delta" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Effect", propOrder = {
    "subeffect",
    "modifiers",
    "change",
    "conditions",
    "subconditions"
})
@XmlSeeAlso({
    OneTimeBoostSkillAttackEffect.class,
    SkillLauncherEffect.class,
    DPTransferEffect.class,
    SlowEffect.class,
    SimpleRootEffect.class,
    RecallInstantEffect.class,
    InvulnerableWingEffect.class,
    NoFPConsumEffect.class,
    FallEffect.class,
    PetOrderUseUltraSkillEffect.class,
    AlwaysParryEffect.class,
    OpenAerialEffect.class,
    RootEffect.class,
    BoostSkillCostEffect.class,
    RandomMoveLocEffect.class,
    NoFlyEffect.class,
    DispelEffect.class,
    ChangeHateOnAttackedEffect.class,
    SearchEffect.class,
    CondSkillLauncherEffect.class,
    HideEffect.class,
    AlwaysDodgeEffect.class,
    RebirthEffect.class,
    SnareEffect.class,
    DelayedFpAtkInstantEffect.class,
    StaggerEffect.class,
    BindEffect.class,
    HostileUpEffect.class,
    PulledEffect.class,
    DiseaseEffect.class,
    SignetEffect.class,
    ConfuseEffect.class,
    MagicCounterAtkEffect.class,
    SleepEffect.class,
    BlindEffect.class,
    AlwaysBlockEffect.class,
    DelayedSkillEffect.class,
    SwitchHpMpEffect.class,
    SpinEffect.class,
    StunEffect.class,
    AlwaysResistEffect.class,
    SanctuaryEffect.class,
    ReturnPointEffect.class,
    ShieldEffect.class,
    AbstractDispelEffect.class,
    CloseAerialEffect.class,
    ParalyzeEffect.class,
    AuraEffect.class,
    AbstractHealEffect.class,
    ResurrectEffect.class,
    FearEffect.class,
    ReturnEffect.class,
    DamageEffect.class,
    StumbleEffect.class,
    TransformEffect.class,
    BufEffect.class,
    SilenceEffect.class,
    AbstractOverTimeEffect.class,
    SummonEffect.class
})
public abstract class Effect {

    protected SubEffect subeffect;
    protected ActionModifiers modifiers;
    protected List<Change> change;
    protected Conditions conditions;
    protected Conditions subconditions;
    @XmlAttribute
    protected Integer hopa;
    @XmlAttribute
    protected Integer hopb;
    @XmlAttribute
    protected HopType hoptype;
    @XmlAttribute
    protected Integer critadddmg1;
    @XmlAttribute
    protected Integer critadddmg2;
    @XmlAttribute
    protected Integer critprobmod2;
    @XmlAttribute(name = "preeffect_prob")
    protected Integer preeffectProb;
    @XmlAttribute
    protected String preeffect;
    @XmlAttribute
    protected SkillElement element;
    @XmlAttribute
    protected Integer hittypeprob2;
    @XmlAttribute
    protected HitType hittype;
    @XmlAttribute
    protected Boolean mrresist;
    @XmlAttribute
    protected Integer accmod1;
    @XmlAttribute
    protected Integer accmod2;
    @XmlAttribute
    protected Boolean noresist;
    @XmlAttribute
    protected Integer basiclvl;
    @XmlAttribute
    protected Integer e;
    @XmlAttribute
    protected Integer effectid;
    @XmlAttribute
    protected Integer randomtime;
    @XmlAttribute
    protected Integer duration1;
    @XmlAttribute
    protected Integer duration2;
    @XmlAttribute
    protected Boolean onfly;
    @XmlAttribute
    protected Integer delta;
    @XmlAttribute
    protected Integer value;

    /**
     * Gets the value of the subeffect property.
     * 
     * @return
     *     possible object is
     *     {@link SubEffect }
     *     
     */
    public SubEffect getSubeffect() {
        return subeffect;
    }

    /**
     * Sets the value of the subeffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubEffect }
     *     
     */
    public void setSubeffect(SubEffect value) {
        this.subeffect = value;
    }

    /**
     * Gets the value of the modifiers property.
     * 
     * @return
     *     possible object is
     *     {@link ActionModifiers }
     *     
     */
    public ActionModifiers getModifiers() {
        return modifiers;
    }

    /**
     * Sets the value of the modifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionModifiers }
     *     
     */
    public void setModifiers(ActionModifiers value) {
        this.modifiers = value;
    }

    /**
     * Gets the value of the change property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the change property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Change }
     * 
     * 
     */
    public List<Change> getChange() {
        if (change == null) {
            change = new ArrayList<Change>();
        }
        return this.change;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link Conditions }
     *     
     */
    public Conditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *     
     */
    public void setConditions(Conditions value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the subconditions property.
     * 
     * @return
     *     possible object is
     *     {@link Conditions }
     *     
     */
    public Conditions getSubconditions() {
        return subconditions;
    }

    /**
     * Sets the value of the subconditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *     
     */
    public void setSubconditions(Conditions value) {
        this.subconditions = value;
    }

    /**
     * Gets the value of the hopa property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHopa() {
        return hopa;
    }

    /**
     * Sets the value of the hopa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHopa(Integer value) {
        this.hopa = value;
    }

    /**
     * Gets the value of the hopb property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHopb() {
        return hopb;
    }

    /**
     * Sets the value of the hopb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHopb(Integer value) {
        this.hopb = value;
    }

    /**
     * Gets the value of the hoptype property.
     * 
     * @return
     *     possible object is
     *     {@link HopType }
     *     
     */
    public HopType getHoptype() {
        return hoptype;
    }

    /**
     * Sets the value of the hoptype property.
     * 
     * @param value
     *     allowed object is
     *     {@link HopType }
     *     
     */
    public void setHoptype(HopType value) {
        this.hoptype = value;
    }

    /**
     * Gets the value of the critadddmg1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCritadddmg1() {
        return critadddmg1;
    }

    /**
     * Sets the value of the critadddmg1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCritadddmg1(Integer value) {
        this.critadddmg1 = value;
    }

    /**
     * Gets the value of the critadddmg2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCritadddmg2() {
        return critadddmg2;
    }

    /**
     * Sets the value of the critadddmg2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCritadddmg2(Integer value) {
        this.critadddmg2 = value;
    }

    /**
     * Gets the value of the critprobmod2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCritprobmod2() {
        return critprobmod2;
    }

    /**
     * Sets the value of the critprobmod2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCritprobmod2(Integer value) {
        this.critprobmod2 = value;
    }

    /**
     * Gets the value of the preeffectProb property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPreeffectProb() {
        return preeffectProb;
    }

    /**
     * Sets the value of the preeffectProb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPreeffectProb(Integer value) {
        this.preeffectProb = value;
    }

    /**
     * Gets the value of the preeffect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreeffect() {
        return preeffect;
    }

    /**
     * Sets the value of the preeffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreeffect(String value) {
        this.preeffect = value;
    }

    /**
     * Gets the value of the element property.
     * 
     * @return
     *     possible object is
     *     {@link SkillElement }
     *     
     */
    public SkillElement getElement() {
        return element;
    }

    /**
     * Sets the value of the element property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkillElement }
     *     
     */
    public void setElement(SkillElement value) {
        this.element = value;
    }

    /**
     * Gets the value of the hittypeprob2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getHittypeprob2() {
        if (hittypeprob2 == null) {
            return  100;
        } else {
            return hittypeprob2;
        }
    }

    /**
     * Sets the value of the hittypeprob2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHittypeprob2(Integer value) {
        this.hittypeprob2 = value;
    }

    /**
     * Gets the value of the hittype property.
     * 
     * @return
     *     possible object is
     *     {@link HitType }
     *     
     */
    public HitType getHittype() {
        if (hittype == null) {
            return HitType.EVERYHIT;
        } else {
            return hittype;
        }
    }

    /**
     * Sets the value of the hittype property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitType }
     *     
     */
    public void setHittype(HitType value) {
        this.hittype = value;
    }

    /**
     * Gets the value of the mrresist property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getMrresist() {
        if (mrresist == null) {
            return true;
        } else {
            return mrresist;
        }
    }

    /**
     * Sets the value of the mrresist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMrresist(Boolean value) {
        this.mrresist = value;
    }

    /**
     * Gets the value of the accmod1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccmod1() {
        return accmod1;
    }

    /**
     * Sets the value of the accmod1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccmod1(Integer value) {
        this.accmod1 = value;
    }

    /**
     * Gets the value of the accmod2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccmod2() {
        return accmod2;
    }

    /**
     * Sets the value of the accmod2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccmod2(Integer value) {
        this.accmod2 = value;
    }

    /**
     * Gets the value of the noresist property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getNoresist() {
        if (noresist == null) {
            return false;
        } else {
            return noresist;
        }
    }

    /**
     * Sets the value of the noresist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoresist(Boolean value) {
        this.noresist = value;
    }

    /**
     * Gets the value of the basiclvl property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBasiclvl() {
        return basiclvl;
    }

    /**
     * Sets the value of the basiclvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBasiclvl(Integer value) {
        this.basiclvl = value;
    }

    /**
     * Gets the value of the e property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getE() {
        return e;
    }

    /**
     * Sets the value of the e property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setE(Integer value) {
        this.e = value;
    }

    /**
     * Gets the value of the effectid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEffectid() {
        return effectid;
    }

    /**
     * Sets the value of the effectid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEffectid(Integer value) {
        this.effectid = value;
    }

    /**
     * Gets the value of the randomtime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRandomtime() {
        return randomtime;
    }

    /**
     * Sets the value of the randomtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRandomtime(Integer value) {
        this.randomtime = value;
    }

    /**
     * Gets the value of the duration1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDuration1() {
        return duration1;
    }

    /**
     * Sets the value of the duration1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDuration1(Integer value) {
        this.duration1 = value;
    }

    /**
     * Gets the value of the duration2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDuration2() {
        return duration2;
    }

    /**
     * Sets the value of the duration2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDuration2(Integer value) {
        this.duration2 = value;
    }

    /**
     * Gets the value of the onfly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getOnfly() {
        if (onfly == null) {
            return false;
        } else {
            return onfly;
        }
    }

    /**
     * Sets the value of the onfly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnfly(Boolean value) {
        this.onfly = value;
    }

    /**
     * Gets the value of the delta property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDelta() {
        return delta;
    }

    /**
     * Sets the value of the delta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDelta(Integer value) {
        this.delta = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setValue(Integer value) {
        this.value = value;
    }

}
