//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnchantItemAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnchantItemAction">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractItemAction">
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="min_level" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="max_level" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="chance" type="{http://www.w3.org/2001/XMLSchema}float" default="0" />
 *       &lt;attribute name="manastone_only" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnchantItemAction")
public class EnchantItemAction
    extends AbstractItemAction
{

    @XmlAttribute
    protected Integer count;
    @XmlAttribute(name = "min_level")
    protected Integer minLevel;
    @XmlAttribute(name = "max_level")
    protected Integer maxLevel;
    @XmlAttribute
    protected Float chance;
    @XmlAttribute(name = "manastone_only")
    protected Boolean manastoneOnly;

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCount() {
        if (count == null) {
            return  0;
        } else {
            return count;
        }
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCount(Integer value) {
        this.count = value;
    }

    /**
     * Gets the value of the minLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMinLevel() {
        if (minLevel == null) {
            return  0;
        } else {
            return minLevel;
        }
    }

    /**
     * Sets the value of the minLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinLevel(Integer value) {
        this.minLevel = value;
    }

    /**
     * Gets the value of the maxLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxLevel() {
        if (maxLevel == null) {
            return  0;
        } else {
            return maxLevel;
        }
    }

    /**
     * Sets the value of the maxLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxLevel(Integer value) {
        this.maxLevel = value;
    }

    /**
     * Gets the value of the chance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getChance() {
        if (chance == null) {
            return  0.0F;
        } else {
            return chance;
        }
    }

    /**
     * Sets the value of the chance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setChance(Float value) {
        this.chance = value;
    }

    /**
     * Gets the value of the manastoneOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getManastoneOnly() {
        if (manastoneOnly == null) {
            return false;
        } else {
            return manastoneOnly;
        }
    }

    /**
     * Sets the value of the manastoneOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setManastoneOnly(Boolean value) {
        this.manastoneOnly = value;
    }

}
