//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Godstone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Godstone">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="skillid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="skilllvl" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="probability" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="probabilityleft" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Godstone")
public class Godstone {

    @XmlAttribute
    protected Integer skillid;
    @XmlAttribute
    protected Integer skilllvl;
    @XmlAttribute
    protected Integer probability;
    @XmlAttribute
    protected Integer probabilityleft;

    /**
     * Gets the value of the skillid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSkillid() {
        return skillid;
    }

    /**
     * Sets the value of the skillid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSkillid(Integer value) {
        this.skillid = value;
    }

    /**
     * Gets the value of the skilllvl property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSkilllvl() {
        return skilllvl;
    }

    /**
     * Sets the value of the skilllvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSkilllvl(Integer value) {
        this.skilllvl = value;
    }

    /**
     * Gets the value of the probability property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProbability() {
        return probability;
    }

    /**
     * Sets the value of the probability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProbability(Integer value) {
        this.probability = value;
    }

    /**
     * Gets the value of the probabilityleft property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProbabilityleft() {
        return probabilityleft;
    }

    /**
     * Sets the value of the probabilityleft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProbabilityleft(Integer value) {
        this.probabilityleft = value;
    }

}
