//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HealCastorOnAttackedEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HealCastorOnAttackedEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractHealEffect">
 *       &lt;attribute name="type" use="required" type="{}HealType" />
 *       &lt;attribute name="range" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HealCastorOnAttackedEffect")
public class HealCastorOnAttackedEffect
    extends AbstractHealEffect
{

    @XmlAttribute(required = true)
    protected HealType type;
    @XmlAttribute(required = true)
    protected float range;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link HealType }
     *     
     */
    public HealType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealType }
     *     
     */
    public void setType(HealType value) {
        this.type = value;
    }

    /**
     * Gets the value of the range property.
     * 
     */
    public float getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     */
    public void setRange(float value) {
        this.range = value;
    }

}
