//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Improvement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Improvement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="way" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="price2" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="price1" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="burn_defend" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="burn_attack" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Improvement")
public class Improvement {

    @XmlAttribute(required = true)
    protected int way;
    @XmlAttribute
    protected Integer price2;
    @XmlAttribute
    protected Integer price1;
    @XmlAttribute(name = "burn_defend")
    protected Integer burnDefend;
    @XmlAttribute(name = "burn_attack")
    protected Integer burnAttack;
    @XmlAttribute
    protected Integer level;

    /**
     * Gets the value of the way property.
     * 
     */
    public int getWay() {
        return way;
    }

    /**
     * Sets the value of the way property.
     * 
     */
    public void setWay(int value) {
        this.way = value;
    }

    /**
     * Gets the value of the price2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrice2() {
        return price2;
    }

    /**
     * Sets the value of the price2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrice2(Integer value) {
        this.price2 = value;
    }

    /**
     * Gets the value of the price1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrice1() {
        return price1;
    }

    /**
     * Sets the value of the price1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrice1(Integer value) {
        this.price1 = value;
    }

    /**
     * Gets the value of the burnDefend property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBurnDefend() {
        return burnDefend;
    }

    /**
     * Sets the value of the burnDefend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBurnDefend(Integer value) {
        this.burnDefend = value;
    }

    /**
     * Gets the value of the burnAttack property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBurnAttack() {
        return burnAttack;
    }

    /**
     * Sets the value of the burnAttack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBurnAttack(Integer value) {
        this.burnAttack = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLevel(Integer value) {
        this.level = value;
    }

}
