//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="modifiers" type="{}Modifiers" minOccurs="0"/>
 *         &lt;element name="actions" type="{}ItemActions" minOccurs="0"/>
 *         &lt;element name="godstone" type="{}Godstone" minOccurs="0"/>
 *         &lt;element name="stigma" type="{}Stigma" minOccurs="0"/>
 *         &lt;element name="weapon_stats" type="{}WeaponStats" minOccurs="0"/>
 *         &lt;element name="tradein_list" type="{}TradeinList" minOccurs="0"/>
 *         &lt;element name="acquisition" type="{}Acquisition" minOccurs="0"/>
 *         &lt;element name="improve" type="{}Improvement" minOccurs="0"/>
 *         &lt;element name="uselimits" type="{}UseLimits" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="activate_count" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="activate_target" type="{}ItemActivateTarget" />
 *       &lt;attribute name="expire_time" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="temp_exchange_time" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="m_slots_r" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="m_slots" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="return_alias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="return_world" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="equipment_type" type="{}equipType" />
 *       &lt;attribute name="slot" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="weapon_boost" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="attack_type" type="{}ItemAttackType" />
 *       &lt;attribute name="attack_gap" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="restrict_max" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="restrict" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="option_slot_bonus" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="rnd_bonus" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="bonus_apply" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="no_enchant" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="dye" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="race" type="{}itemRace" />
 *       &lt;attribute name="price" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="quality" type="{}itemQuality" />
 *       &lt;attribute name="category" type="{}Category" />
 *       &lt;attribute name="item_type" type="{}itemType" />
 *       &lt;attribute name="max_stack_count" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="armor_type" type="{}armorType" />
 *       &lt;attribute name="weapon_type" type="{}weaponType" />
 *       &lt;attribute name="mask" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="id" use="required" type="{}itemId" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemTemplate", propOrder = {
    "modifiersAndActionsAndGodstone"
})
public class ItemTemplate {

    @XmlElements({
        @XmlElement(name = "tradein_list", type = TradeinList.class),
        @XmlElement(name = "stigma", type = Stigma.class),
        @XmlElement(name = "weapon_stats", type = WeaponStats.class),
        @XmlElement(name = "improve", type = Improvement.class),
        @XmlElement(name = "uselimits", type = UseLimits.class),
        @XmlElement(name = "godstone", type = Godstone.class),
        @XmlElement(name = "actions", type = ItemActions.class),
        @XmlElement(name = "acquisition", type = Acquisition.class),
        @XmlElement(name = "modifiers", type = Modifiers.class)
    })
    protected List<Object> modifiersAndActionsAndGodstone;
    @XmlAttribute(name = "activate_count")
    protected Integer activateCount;
    @XmlAttribute(name = "activate_target")
    protected ItemActivateTarget activateTarget;
    @XmlAttribute(name = "expire_time")
    protected Integer expireTime;
    @XmlAttribute(name = "temp_exchange_time")
    protected Integer tempExchangeTime;
    @XmlAttribute(name = "m_slots_r")
    protected Integer mSlotsR;
    @XmlAttribute(name = "m_slots")
    protected Integer mSlots;
    @XmlAttribute(name = "return_alias")
    protected String returnAlias;
    @XmlAttribute(name = "return_world")
    protected Integer returnWorld;
    @XmlAttribute(name = "equipment_type")
    protected EquipType equipmentType;
    @XmlAttribute
    protected Integer slot;
    @XmlAttribute(name = "weapon_boost")
    protected Integer weaponBoost;
    @XmlAttribute(name = "attack_type")
    protected ItemAttackType attackType;
    @XmlAttribute(name = "attack_gap")
    protected Float attackGap;
    @XmlAttribute
    protected Integer desc;
    @XmlAttribute(name = "restrict_max")
    protected String restrictMax;
    @XmlAttribute
    protected String restrict;
    @XmlAttribute(name = "option_slot_bonus")
    protected Integer optionSlotBonus;
    @XmlAttribute(name = "rnd_bonus")
    protected Integer rndBonus;
    @XmlAttribute(name = "bonus_apply")
    protected String bonusApply;
    @XmlAttribute(name = "no_enchant")
    protected Boolean noEnchant;
    @XmlAttribute
    protected Boolean dye;
    @XmlAttribute
    protected ItemRace race;
    @XmlAttribute
    protected Integer price;
    @XmlAttribute
    protected ItemQuality quality;
    @XmlAttribute
    protected Category category;
    @XmlAttribute(name = "item_type")
    protected ItemType itemType;
    @XmlAttribute(name = "max_stack_count")
    protected Integer maxStackCount;
    @XmlAttribute(name = "armor_type")
    protected String armorType;
    @XmlAttribute(name = "weapon_type")
    protected String weaponType;
    @XmlAttribute
    protected Integer mask;
    @XmlAttribute
    protected Integer level;
    @XmlAttribute(required = true)
    protected int id;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the modifiersAndActionsAndGodstone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modifiersAndActionsAndGodstone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModifiersAndActionsAndGodstone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TradeinList }
     * {@link Stigma }
     * {@link WeaponStats }
     * {@link Improvement }
     * {@link UseLimits }
     * {@link Godstone }
     * {@link ItemActions }
     * {@link Acquisition }
     * {@link Modifiers }
     * 
     * 
     */
    public List<Object> getModifiersAndActionsAndGodstone() {
        if (modifiersAndActionsAndGodstone == null) {
            modifiersAndActionsAndGodstone = new ArrayList<Object>();
        }
        return this.modifiersAndActionsAndGodstone;
    }

    /**
     * Gets the value of the activateCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getActivateCount() {
        return activateCount;
    }

    /**
     * Sets the value of the activateCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setActivateCount(Integer value) {
        this.activateCount = value;
    }

    /**
     * Gets the value of the activateTarget property.
     * 
     * @return
     *     possible object is
     *     {@link ItemActivateTarget }
     *     
     */
    public ItemActivateTarget getActivateTarget() {
        return activateTarget;
    }

    /**
     * Sets the value of the activateTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemActivateTarget }
     *     
     */
    public void setActivateTarget(ItemActivateTarget value) {
        this.activateTarget = value;
    }

    /**
     * Gets the value of the expireTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExpireTime() {
        return expireTime;
    }

    /**
     * Sets the value of the expireTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExpireTime(Integer value) {
        this.expireTime = value;
    }

    /**
     * Gets the value of the tempExchangeTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTempExchangeTime() {
        return tempExchangeTime;
    }

    /**
     * Sets the value of the tempExchangeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTempExchangeTime(Integer value) {
        this.tempExchangeTime = value;
    }

    /**
     * Gets the value of the mSlotsR property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMSlotsR() {
        return mSlotsR;
    }

    /**
     * Sets the value of the mSlotsR property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMSlotsR(Integer value) {
        this.mSlotsR = value;
    }

    /**
     * Gets the value of the mSlots property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMSlots() {
        return mSlots;
    }

    /**
     * Sets the value of the mSlots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMSlots(Integer value) {
        this.mSlots = value;
    }

    /**
     * Gets the value of the returnAlias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnAlias() {
        return returnAlias;
    }

    /**
     * Sets the value of the returnAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnAlias(String value) {
        this.returnAlias = value;
    }

    /**
     * Gets the value of the returnWorld property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReturnWorld() {
        return returnWorld;
    }

    /**
     * Sets the value of the returnWorld property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReturnWorld(Integer value) {
        this.returnWorld = value;
    }

    /**
     * Gets the value of the equipmentType property.
     * 
     * @return
     *     possible object is
     *     {@link EquipType }
     *     
     */
    public EquipType getEquipmentType() {
        return equipmentType;
    }

    /**
     * Sets the value of the equipmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipType }
     *     
     */
    public void setEquipmentType(EquipType value) {
        this.equipmentType = value;
    }

    /**
     * Gets the value of the slot property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSlot() {
        return slot;
    }

    /**
     * Sets the value of the slot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSlot(Integer value) {
        this.slot = value;
    }

    /**
     * Gets the value of the weaponBoost property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWeaponBoost() {
        return weaponBoost;
    }

    /**
     * Sets the value of the weaponBoost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWeaponBoost(Integer value) {
        this.weaponBoost = value;
    }

    /**
     * Gets the value of the attackType property.
     * 
     * @return
     *     possible object is
     *     {@link ItemAttackType }
     *     
     */
    public ItemAttackType getAttackType() {
        return attackType;
    }

    /**
     * Sets the value of the attackType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemAttackType }
     *     
     */
    public void setAttackType(ItemAttackType value) {
        this.attackType = value;
    }

    /**
     * Gets the value of the attackGap property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAttackGap() {
        return attackGap;
    }

    /**
     * Sets the value of the attackGap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAttackGap(Float value) {
        this.attackGap = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDesc(Integer value) {
        this.desc = value;
    }

    /**
     * Gets the value of the restrictMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestrictMax() {
        return restrictMax;
    }

    /**
     * Sets the value of the restrictMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestrictMax(String value) {
        this.restrictMax = value;
    }

    /**
     * Gets the value of the restrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestrict() {
        return restrict;
    }

    /**
     * Sets the value of the restrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestrict(String value) {
        this.restrict = value;
    }

    /**
     * Gets the value of the optionSlotBonus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOptionSlotBonus() {
        return optionSlotBonus;
    }

    /**
     * Sets the value of the optionSlotBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOptionSlotBonus(Integer value) {
        this.optionSlotBonus = value;
    }

    /**
     * Gets the value of the rndBonus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRndBonus() {
        return rndBonus;
    }

    /**
     * Sets the value of the rndBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRndBonus(Integer value) {
        this.rndBonus = value;
    }

    /**
     * Gets the value of the bonusApply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBonusApply() {
        return bonusApply;
    }

    /**
     * Sets the value of the bonusApply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBonusApply(String value) {
        this.bonusApply = value;
    }

    /**
     * Gets the value of the noEnchant property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getNoEnchant() {
        return noEnchant;
    }

    /**
     * Sets the value of the noEnchant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoEnchant(Boolean value) {
        this.noEnchant = value;
    }

    /**
     * Gets the value of the dye property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getDye() {
        return dye;
    }

    /**
     * Sets the value of the dye property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDye(Boolean value) {
        this.dye = value;
    }

    /**
     * Gets the value of the race property.
     * 
     * @return
     *     possible object is
     *     {@link ItemRace }
     *     
     */
    public ItemRace getRace() {
        return race;
    }

    /**
     * Sets the value of the race property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemRace }
     *     
     */
    public void setRace(ItemRace value) {
        this.race = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrice(Integer value) {
        this.price = value;
    }

    /**
     * Gets the value of the quality property.
     * 
     * @return
     *     possible object is
     *     {@link ItemQuality }
     *     
     */
    public ItemQuality getQuality() {
        return quality;
    }

    /**
     * Sets the value of the quality property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemQuality }
     *     
     */
    public void setQuality(ItemQuality value) {
        this.quality = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the itemType property.
     * 
     * @return
     *     possible object is
     *     {@link ItemType }
     *     
     */
    public ItemType getItemType() {
        return itemType;
    }

    /**
     * Sets the value of the itemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemType }
     *     
     */
    public void setItemType(ItemType value) {
        this.itemType = value;
    }

    /**
     * Gets the value of the maxStackCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxStackCount() {
        return maxStackCount;
    }

    /**
     * Sets the value of the maxStackCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxStackCount(Integer value) {
        this.maxStackCount = value;
    }

    /**
     * Gets the value of the armorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArmorType() {
        return armorType;
    }

    /**
     * Sets the value of the armorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArmorType(String value) {
        this.armorType = value;
    }

    /**
     * Gets the value of the weaponType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeaponType() {
        return weaponType;
    }

    /**
     * Sets the value of the weaponType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeaponType(String value) {
        this.weaponType = value;
    }

    /**
     * Gets the value of the mask property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMask() {
        return mask;
    }

    /**
     * Sets the value of the mask property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMask(Integer value) {
        this.mask = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLevel(Integer value) {
        this.level = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
