//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for itemSlot.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="itemSlot">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MAIN_HAND"/>
 *     &lt;enumeration value="SUB_HAND"/>
 *     &lt;enumeration value="HAND_MAIN_OR_SUB"/>
 *     &lt;enumeration value="HELMET"/>
 *     &lt;enumeration value="TORSO"/>
 *     &lt;enumeration value="GLOVES"/>
 *     &lt;enumeration value="BOOTS"/>
 *     &lt;enumeration value="EARRINGS_LEFT"/>
 *     &lt;enumeration value="EARRINGS_RIGHT"/>
 *     &lt;enumeration value="EARRING_RIGHT_OR_LEFT"/>
 *     &lt;enumeration value="RING_LEFT"/>
 *     &lt;enumeration value="RING_RIGHT"/>
 *     &lt;enumeration value="RING_RIGHT_OR_LEFT"/>
 *     &lt;enumeration value="NECKLACE"/>
 *     &lt;enumeration value="SHOULDER"/>
 *     &lt;enumeration value="PANTS"/>
 *     &lt;enumeration value="POWER_SHARD_RIGHT"/>
 *     &lt;enumeration value="POWER_SHARD_LEFT"/>
 *     &lt;enumeration value="SHARD_RIGHT_OR_LEFT"/>
 *     &lt;enumeration value="WINGS"/>
 *     &lt;enumeration value="WAIST"/>
 *     &lt;enumeration value="TORSO_GLOVE_FOOT_SHOULDER_LEG"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "itemSlot")
@XmlEnum
public enum ItemSlot {

    MAIN_HAND,
    SUB_HAND,
    HAND_MAIN_OR_SUB,
    HELMET,
    TORSO,
    GLOVES,
    BOOTS,
    EARRINGS_LEFT,
    EARRINGS_RIGHT,
    EARRING_RIGHT_OR_LEFT,
    RING_LEFT,
    RING_RIGHT,
    RING_RIGHT_OR_LEFT,
    NECKLACE,
    SHOULDER,
    PANTS,
    POWER_SHARD_RIGHT,
    POWER_SHARD_LEFT,
    SHARD_RIGHT_OR_LEFT,
    WINGS,
    WAIST,
    TORSO_GLOVE_FOOT_SHOULDER_LEG;

    public String value() {
        return name();
    }

    public static ItemSlot fromValue(String v) {
        return valueOf(v);
    }

}
