//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for modifiersenum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="modifiersenum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MAXDP"/>
 *     &lt;enumeration value="MAXHP"/>
 *     &lt;enumeration value="MAXHP_DUPE"/>
 *     &lt;enumeration value="MAXMP"/>
 *     &lt;enumeration value="REGEN_HP"/>
 *     &lt;enumeration value="REGEN_MP"/>
 *     &lt;enumeration value="AGILITY"/>
 *     &lt;enumeration value="AGILITY_DUPE"/>
 *     &lt;enumeration value="BLOCK"/>
 *     &lt;enumeration value="EVASION"/>
 *     &lt;enumeration value="CONCENTRATION"/>
 *     &lt;enumeration value="WILL"/>
 *     &lt;enumeration value="HEALTH"/>
 *     &lt;enumeration value="ACCURACY"/>
 *     &lt;enumeration value="KNOWLEDGE"/>
 *     &lt;enumeration value="PARRY"/>
 *     &lt;enumeration value="POWER"/>
 *     &lt;enumeration value="SPEED"/>
 *     &lt;enumeration value="HIT_COUNT"/>
 *     &lt;enumeration value="ATTACK_RANGE"/>
 *     &lt;enumeration value="ATTACK_SPEED"/>
 *     &lt;enumeration value="PHYSICAL_ATTACK"/>
 *     &lt;enumeration value="PHYSICAL_ACCURACY"/>
 *     &lt;enumeration value="PHYSICAL_CRITICAL"/>
 *     &lt;enumeration value="PHYSICAL_DEFENSE"/>
 *     &lt;enumeration value="MAIN_HAND_ACCURACY"/>
 *     &lt;enumeration value="MAIN_HAND_CRITICAL"/>
 *     &lt;enumeration value="MAIN_HAND_POWER"/>
 *     &lt;enumeration value="OFF_HAND_ACCURACY"/>
 *     &lt;enumeration value="OFF_HAND_CRITICAL"/>
 *     &lt;enumeration value="OFF_HAND_POWER"/>
 *     &lt;enumeration value="MAGICAL_ATTACK"/>
 *     &lt;enumeration value="MAGICAL_ACCURACY"/>
 *     &lt;enumeration value="MAGICAL_CRITICAL"/>
 *     &lt;enumeration value="MAGICAL_RESIST"/>
 *     &lt;enumeration value="MAX_DAMAGES"/>
 *     &lt;enumeration value="MIN_DAMAGES"/>
 *     &lt;enumeration value="IS_MAGICAL_ATTACK"/>
 *     &lt;enumeration value="EARTH_RESISTANCE"/>
 *     &lt;enumeration value="FIRE_RESISTANCE"/>
 *     &lt;enumeration value="WIND_RESISTANCE"/>
 *     &lt;enumeration value="WATER_RESISTANCE"/>
 *     &lt;enumeration value="DARK_RESISTANCE"/>
 *     &lt;enumeration value="LIGHT_RESISTANCE"/>
 *     &lt;enumeration value="BOOST_MAGICAL_SKILL"/>
 *     &lt;enumeration value="BOOST_SPELL_ATTACK"/>
 *     &lt;enumeration value="BOOST_CASTING_TIME_HEAL"/>
 *     &lt;enumeration value="BOOST_CASTING_TIME_ATTACK"/>
 *     &lt;enumeration value="BOOST_CASTING_TIME_TRAP"/>
 *     &lt;enumeration value="BOOST_CASTING_TIME_SUMMON"/>
 *     &lt;enumeration value="BOOST_CASTING_TIME_SUMMONHOMING"/>
 *     &lt;enumeration value="BOOST_CASTING_TIME"/>
 *     &lt;enumeration value="BOOST_HATE"/>
 *     &lt;enumeration value="FLY_TIME"/>
 *     &lt;enumeration value="FLY_SPEED"/>
 *     &lt;enumeration value="PVP_ATTACK_RATIO"/>
 *     &lt;enumeration value="PVP_DEFEND_RATIO"/>
 *     &lt;enumeration value="PVP_DEFEND_RATIO_MAGICAL"/>
 *     &lt;enumeration value="PVP_DEFEND_RATIO_PHYSICAL"/>
 *     &lt;enumeration value="PVP_ATTACK_RATIO_PHYSICAL"/>
 *     &lt;enumeration value="PVP_ATTACK_RATIO_MAGICAL"/>
 *     &lt;enumeration value="PVP_PHYSICAL_ATTACK"/>
 *     &lt;enumeration value="PVP_PHYSICAL_DEFEND"/>
 *     &lt;enumeration value="PVP_MAGICAL_ATTACK"/>
 *     &lt;enumeration value="PVP_MAGICAL_DEFEND"/>
 *     &lt;enumeration value="DAMAGE_REDUCE"/>
 *     &lt;enumeration value="BLEED_RESISTANCE"/>
 *     &lt;enumeration value="BLIND_RESISTANCE"/>
 *     &lt;enumeration value="CHARM_RESISTANCE"/>
 *     &lt;enumeration value="CONFUSE_RESISTANCE"/>
 *     &lt;enumeration value="CURSE_RESISTANCE"/>
 *     &lt;enumeration value="DEFORM_RESISTANCE"/>
 *     &lt;enumeration value="DISEASE_RESISTANCE"/>
 *     &lt;enumeration value="FEAR_RESISTANCE"/>
 *     &lt;enumeration value="OPENAREIAL_RESISTANCE"/>
 *     &lt;enumeration value="PARALYZE_RESISTANCE"/>
 *     &lt;enumeration value="PERIFICATION_RESISTANCE"/>
 *     &lt;enumeration value="POISON_RESISTANCE"/>
 *     &lt;enumeration value="ROOT_RESISTANCE"/>
 *     &lt;enumeration value="SILENCE_RESISTANCE"/>
 *     &lt;enumeration value="SLEEP_RESISTANCE"/>
 *     &lt;enumeration value="SLOW_RESISTANCE"/>
 *     &lt;enumeration value="SNARE_RESISTANCE"/>
 *     &lt;enumeration value="SPIN_RESISTANCE"/>
 *     &lt;enumeration value="STAGGER_RESISTANCE"/>
 *     &lt;enumeration value="STUMBLE_RESISTANCE"/>
 *     &lt;enumeration value="STUN_RESISTANCE"/>
 *     &lt;enumeration value="SILENCE_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="PARALYZE_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="STAGGER_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="STUMBLE_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="STUN_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="REGEN_FP"/>
 *     &lt;enumeration value="HEAL_BOOST"/>
 *     &lt;enumeration value="HEAL_SKILL_BOOST"/>
 *     &lt;enumeration value="ALLRESIST"/>
 *     &lt;enumeration value="STUNLIKE_RESISTANCE"/>
 *     &lt;enumeration value="ELEMENTAL_RESISTANCE_DARK"/>
 *     &lt;enumeration value="ELEMENTAL_RESISTANCE_LIGHT"/>
 *     &lt;enumeration value="MAGICAL_CRITICAL_RESIST"/>
 *     &lt;enumeration value="MAGICAL_CRITICAL_DAMAGE_REDUCE"/>
 *     &lt;enumeration value="PHYSICAL_CRITICAL_RESIST"/>
 *     &lt;enumeration value="PHYSICAL_CRITICAL_DAMAGE_REDUCE"/>
 *     &lt;enumeration value="ERFIRE"/>
 *     &lt;enumeration value="ERAIR"/>
 *     &lt;enumeration value="EREARTH"/>
 *     &lt;enumeration value="ERWATER"/>
 *     &lt;enumeration value="ABNORMAL_RESISTANCE_ALL"/>
 *     &lt;enumeration value="ALLPARA"/>
 *     &lt;enumeration value="KNOWIL"/>
 *     &lt;enumeration value="AGIDEX"/>
 *     &lt;enumeration value="STRVIT"/>
 *     &lt;enumeration value="BOOST_HUNTING_XP_RATE"/>
 *     &lt;enumeration value="BOOST_GROUP_HUNTING_XP_RATE"/>
 *     &lt;enumeration value="BOOST_QUEST_XP_RATE"/>
 *     &lt;enumeration value="BOOST_CRAFTING_XP_RATE"/>
 *     &lt;enumeration value="BOOST_GATHERING_XP_RATE"/>
 *     &lt;enumeration value="BOOST_DROP_RATE"/>
 *     &lt;enumeration value="BOOST_MANTRA_RANGE"/>
 *     &lt;enumeration value="MAGICAL_DEFEND"/>
 *     &lt;enumeration value="MAGIC_SKILL_BOOST_RESIST"/>
 *     &lt;enumeration value="POISON_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="BLEED_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="SLEEP_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="ROOT_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="BLIND_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="CHARM_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="DISEASE_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="FEAR_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="SPIN_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="CURSE_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="CONFUSE_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="PERIFICATION_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="OPENAREIAL_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="SNARE_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="SLOW_RESISTANCE_PENETRATION"/>
 *     &lt;enumeration value="BOOST_DURATION_BUFF"/>
 *     &lt;enumeration value="BOOST_RESIST_DEBUFF"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "modifiersenum")
@XmlEnum
public enum Modifiersenum {

    MAXDP,
    MAXHP,
    MAXHP_DUPE,
    MAXMP,
    REGEN_HP,
    REGEN_MP,
    AGILITY,
    AGILITY_DUPE,
    BLOCK,
    EVASION,
    CONCENTRATION,
    WILL,
    HEALTH,
    ACCURACY,
    KNOWLEDGE,
    PARRY,
    POWER,
    SPEED,
    HIT_COUNT,
    ATTACK_RANGE,
    ATTACK_SPEED,
    PHYSICAL_ATTACK,
    PHYSICAL_ACCURACY,
    PHYSICAL_CRITICAL,
    PHYSICAL_DEFENSE,
    MAIN_HAND_ACCURACY,
    MAIN_HAND_CRITICAL,
    MAIN_HAND_POWER,
    OFF_HAND_ACCURACY,
    OFF_HAND_CRITICAL,
    OFF_HAND_POWER,
    MAGICAL_ATTACK,
    MAGICAL_ACCURACY,
    MAGICAL_CRITICAL,
    MAGICAL_RESIST,
    MAX_DAMAGES,
    MIN_DAMAGES,
    IS_MAGICAL_ATTACK,
    EARTH_RESISTANCE,
    FIRE_RESISTANCE,
    WIND_RESISTANCE,
    WATER_RESISTANCE,
    DARK_RESISTANCE,
    LIGHT_RESISTANCE,
    BOOST_MAGICAL_SKILL,
    BOOST_SPELL_ATTACK,
    BOOST_CASTING_TIME_HEAL,
    BOOST_CASTING_TIME_ATTACK,
    BOOST_CASTING_TIME_TRAP,
    BOOST_CASTING_TIME_SUMMON,
    BOOST_CASTING_TIME_SUMMONHOMING,
    BOOST_CASTING_TIME,
    BOOST_HATE,
    FLY_TIME,
    FLY_SPEED,
    PVP_ATTACK_RATIO,
    PVP_DEFEND_RATIO,
    PVP_DEFEND_RATIO_MAGICAL,
    PVP_DEFEND_RATIO_PHYSICAL,
    PVP_ATTACK_RATIO_PHYSICAL,
    PVP_ATTACK_RATIO_MAGICAL,
    PVP_PHYSICAL_ATTACK,
    PVP_PHYSICAL_DEFEND,
    PVP_MAGICAL_ATTACK,
    PVP_MAGICAL_DEFEND,
    DAMAGE_REDUCE,
    BLEED_RESISTANCE,
    BLIND_RESISTANCE,
    CHARM_RESISTANCE,
    CONFUSE_RESISTANCE,
    CURSE_RESISTANCE,
    DEFORM_RESISTANCE,
    DISEASE_RESISTANCE,
    FEAR_RESISTANCE,
    OPENAREIAL_RESISTANCE,
    PARALYZE_RESISTANCE,
    PERIFICATION_RESISTANCE,
    POISON_RESISTANCE,
    ROOT_RESISTANCE,
    SILENCE_RESISTANCE,
    SLEEP_RESISTANCE,
    SLOW_RESISTANCE,
    SNARE_RESISTANCE,
    SPIN_RESISTANCE,
    STAGGER_RESISTANCE,
    STUMBLE_RESISTANCE,
    STUN_RESISTANCE,
    SILENCE_RESISTANCE_PENETRATION,
    PARALYZE_RESISTANCE_PENETRATION,
    STAGGER_RESISTANCE_PENETRATION,
    STUMBLE_RESISTANCE_PENETRATION,
    STUN_RESISTANCE_PENETRATION,
    REGEN_FP,
    HEAL_BOOST,
    HEAL_SKILL_BOOST,
    ALLRESIST,
    STUNLIKE_RESISTANCE,
    ELEMENTAL_RESISTANCE_DARK,
    ELEMENTAL_RESISTANCE_LIGHT,
    MAGICAL_CRITICAL_RESIST,
    MAGICAL_CRITICAL_DAMAGE_REDUCE,
    PHYSICAL_CRITICAL_RESIST,
    PHYSICAL_CRITICAL_DAMAGE_REDUCE,
    ERFIRE,
    ERAIR,
    EREARTH,
    ERWATER,
    ABNORMAL_RESISTANCE_ALL,
    ALLPARA,
    KNOWIL,
    AGIDEX,
    STRVIT,
    BOOST_HUNTING_XP_RATE,
    BOOST_GROUP_HUNTING_XP_RATE,
    BOOST_QUEST_XP_RATE,
    BOOST_CRAFTING_XP_RATE,
    BOOST_GATHERING_XP_RATE,
    BOOST_DROP_RATE,
    BOOST_MANTRA_RANGE,
    MAGICAL_DEFEND,
    MAGIC_SKILL_BOOST_RESIST,
    POISON_RESISTANCE_PENETRATION,
    BLEED_RESISTANCE_PENETRATION,
    SLEEP_RESISTANCE_PENETRATION,
    ROOT_RESISTANCE_PENETRATION,
    BLIND_RESISTANCE_PENETRATION,
    CHARM_RESISTANCE_PENETRATION,
    DISEASE_RESISTANCE_PENETRATION,
    FEAR_RESISTANCE_PENETRATION,
    SPIN_RESISTANCE_PENETRATION,
    CURSE_RESISTANCE_PENETRATION,
    CONFUSE_RESISTANCE_PENETRATION,
    PERIFICATION_RESISTANCE_PENETRATION,
    OPENAREIAL_RESISTANCE_PENETRATION,
    SNARE_RESISTANCE_PENETRATION,
    SLOW_RESISTANCE_PENETRATION,
    BOOST_DURATION_BUFF,
    BOOST_RESIST_DEBUFF;

    public String value() {
        return name();
    }

    public static Modifiersenum fromValue(String v) {
        return valueOf(v);
    }

}
