//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Modifiers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Modifiers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="add" type="{}SimpleModifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sub" type="{}SimpleModifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rate" type="{}SimpleModifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="set" type="{}SimpleModifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="mean" type="{}MeanModifier" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="chance" type="{http://www.w3.org/2001/XMLSchema}float" default="100" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Modifiers", propOrder = {
    "addAndSubAndRate"
})
public class Modifiers {

    @XmlElementRefs({
        @XmlElementRef(name = "mean", type = JAXBElement.class),
        @XmlElementRef(name = "sub", type = JAXBElement.class),
        @XmlElementRef(name = "add", type = JAXBElement.class),
        @XmlElementRef(name = "rate", type = JAXBElement.class),
        @XmlElementRef(name = "set", type = JAXBElement.class)
    })
    protected List<JAXBElement<? extends Modifier>> addAndSubAndRate;
    @XmlAttribute
    protected Float chance;

    /**
     * Gets the value of the addAndSubAndRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addAndSubAndRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddAndSubAndRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SimpleModifier }{@code >}
     * {@link JAXBElement }{@code <}{@link SimpleModifier }{@code >}
     * {@link JAXBElement }{@code <}{@link MeanModifier }{@code >}
     * {@link JAXBElement }{@code <}{@link SimpleModifier }{@code >}
     * {@link JAXBElement }{@code <}{@link SimpleModifier }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Modifier>> getAddAndSubAndRate() {
        if (addAndSubAndRate == null) {
            addAndSubAndRate = new ArrayList<JAXBElement<? extends Modifier>>();
        }
        return this.addAndSubAndRate;
    }

    /**
     * Gets the value of the chance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getChance() {
        if (chance == null) {
            return  100.0F;
        } else {
            return chance;
        }
    }

    /**
     * Sets the value of the chance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setChance(Float value) {
        this.chance = value;
    }

}
