//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.parser.output.aion.skills package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ModifiersSub_QNAME = new QName("", "sub");
    private final static QName _ModifiersRate_QNAME = new QName("", "rate");
    private final static QName _ModifiersSet_QNAME = new QName("", "set");
    private final static QName _ModifiersMean_QNAME = new QName("", "mean");
    private final static QName _ModifiersAdd_QNAME = new QName("", "add");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.parser.output.aion.skills
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MPHealInstantEffect }
     * 
     */
    public MPHealInstantEffect createMPHealInstantEffect() {
        return new MPHealInstantEffect();
    }

    /**
     * Create an instance of {@link FpAttackEffect }
     * 
     */
    public FpAttackEffect createFpAttackEffect() {
        return new FpAttackEffect();
    }

    /**
     * Create an instance of {@link TargetRaceDamageModifier }
     * 
     */
    public TargetRaceDamageModifier createTargetRaceDamageModifier() {
        return new TargetRaceDamageModifier();
    }

    /**
     * Create an instance of {@link SpellAtkDrainEffect }
     * 
     */
    public SpellAtkDrainEffect createSpellAtkDrainEffect() {
        return new SpellAtkDrainEffect();
    }

    /**
     * Create an instance of {@link MoveBehindEffect }
     * 
     */
    public MoveBehindEffect createMoveBehindEffect() {
        return new MoveBehindEffect();
    }

    /**
     * Create an instance of {@link ReturnEffect }
     * 
     */
    public ReturnEffect createReturnEffect() {
        return new ReturnEffect();
    }

    /**
     * Create an instance of {@link MpUsePeriodicAction }
     * 
     */
    public MpUsePeriodicAction createMpUsePeriodicAction() {
        return new MpUsePeriodicAction();
    }

    /**
     * Create an instance of {@link ReadAction }
     * 
     */
    public ReadAction createReadAction() {
        return new ReadAction();
    }

    /**
     * Create an instance of {@link DeboostHealEffect }
     * 
     */
    public DeboostHealEffect createDeboostHealEffect() {
        return new DeboostHealEffect();
    }

    /**
     * Create an instance of {@link PolymorphEffect }
     * 
     */
    public PolymorphEffect createPolymorphEffect() {
        return new PolymorphEffect();
    }

    /**
     * Create an instance of {@link SummonTrapEffect }
     * 
     */
    public SummonTrapEffect createSummonTrapEffect() {
        return new SummonTrapEffect();
    }

    /**
     * Create an instance of {@link SkillTemplate }
     * 
     */
    public SkillTemplate createSkillTemplate() {
        return new SkillTemplate();
    }

    /**
     * Create an instance of {@link ConvertHealEffect }
     * 
     */
    public ConvertHealEffect createConvertHealEffect() {
        return new ConvertHealEffect();
    }

    /**
     * Create an instance of {@link AlwaysBlockEffect }
     * 
     */
    public AlwaysBlockEffect createAlwaysBlockEffect() {
        return new AlwaysBlockEffect();
    }

    /**
     * Create an instance of {@link SubTypeExtendDurationEffect }
     * 
     */
    public SubTypeExtendDurationEffect createSubTypeExtendDurationEffect() {
        return new SubTypeExtendDurationEffect();
    }

    /**
     * Create an instance of {@link AuraEffect }
     * 
     */
    public AuraEffect createAuraEffect() {
        return new AuraEffect();
    }

    /**
     * Create an instance of {@link StatdownEffect }
     * 
     */
    public StatdownEffect createStatdownEffect() {
        return new StatdownEffect();
    }

    /**
     * Create an instance of {@link StaggerEffect }
     * 
     */
    public StaggerEffect createStaggerEffect() {
        return new StaggerEffect();
    }

    /**
     * Create an instance of {@link Change }
     * 
     */
    public Change createChange() {
        return new Change();
    }

    /**
     * Create an instance of {@link BuffSilenceEffect }
     * 
     */
    public BuffSilenceEffect createBuffSilenceEffect() {
        return new BuffSilenceEffect();
    }

    /**
     * Create an instance of {@link EnchantItemAction }
     * 
     */
    public EnchantItemAction createEnchantItemAction() {
        return new EnchantItemAction();
    }

    /**
     * Create an instance of {@link WeaponStats }
     * 
     */
    public WeaponStats createWeaponStats() {
        return new WeaponStats();
    }

    /**
     * Create an instance of {@link OneTimeBoostSkillAttackEffect }
     * 
     */
    public OneTimeBoostSkillAttackEffect createOneTimeBoostSkillAttackEffect() {
        return new OneTimeBoostSkillAttackEffect();
    }

    /**
     * Create an instance of {@link NoFlyingCondition }
     * 
     */
    public NoFlyingCondition createNoFlyingCondition() {
        return new NoFlyingCondition();
    }

    /**
     * Create an instance of {@link FireworksUseAction }
     * 
     */
    public FireworksUseAction createFireworksUseAction() {
        return new FireworksUseAction();
    }

    /**
     * Create an instance of {@link AlwaysParryEffect }
     * 
     */
    public AlwaysParryEffect createAlwaysParryEffect() {
        return new AlwaysParryEffect();
    }

    /**
     * Create an instance of {@link ItemTemplates }
     * 
     */
    public ItemTemplates createItemTemplates() {
        return new ItemTemplates();
    }

    /**
     * Create an instance of {@link EmotionLearnAction }
     * 
     */
    public EmotionLearnAction createEmotionLearnAction() {
        return new EmotionLearnAction();
    }

    /**
     * Create an instance of {@link AnimationAddAction }
     * 
     */
    public AnimationAddAction createAnimationAddAction() {
        return new AnimationAddAction();
    }

    /**
     * Create an instance of {@link SummonBindingGroupGateEffect }
     * 
     */
    public SummonBindingGroupGateEffect createSummonBindingGroupGateEffect() {
        return new SummonBindingGroupGateEffect();
    }

    /**
     * Create an instance of {@link SimpleModifier }
     * 
     */
    public SimpleModifier createSimpleModifier() {
        return new SimpleModifier();
    }

    /**
     * Create an instance of {@link BuffBindEffect }
     * 
     */
    public BuffBindEffect createBuffBindEffect() {
        return new BuffBindEffect();
    }

    /**
     * Create an instance of {@link BoostDropRateEffect }
     * 
     */
    public BoostDropRateEffect createBoostDropRateEffect() {
        return new BoostDropRateEffect();
    }

    /**
     * Create an instance of {@link SwitchHpMpEffect }
     * 
     */
    public SwitchHpMpEffect createSwitchHpMpEffect() {
        return new SwitchHpMpEffect();
    }

    /**
     * Create an instance of {@link SubTypeBoostResistEffect }
     * 
     */
    public SubTypeBoostResistEffect createSubTypeBoostResistEffect() {
        return new SubTypeBoostResistEffect();
    }

    /**
     * Create an instance of {@link HpCondition }
     * 
     */
    public HpCondition createHpCondition() {
        return new HpCondition();
    }

    /**
     * Create an instance of {@link DispelEffect }
     * 
     */
    public DispelEffect createDispelEffect() {
        return new DispelEffect();
    }

    /**
     * Create an instance of {@link ProcHealInstantEffect }
     * 
     */
    public ProcHealInstantEffect createProcHealInstantEffect() {
        return new ProcHealInstantEffect();
    }

    /**
     * Create an instance of {@link OneTimeBoostHealEffect }
     * 
     */
    public OneTimeBoostHealEffect createOneTimeBoostHealEffect() {
        return new OneTimeBoostHealEffect();
    }

    /**
     * Create an instance of {@link DpUseAction }
     * 
     */
    public DpUseAction createDpUseAction() {
        return new DpUseAction();
    }

    /**
     * Create an instance of {@link AlwaysDodgeEffect }
     * 
     */
    public AlwaysDodgeEffect createAlwaysDodgeEffect() {
        return new AlwaysDodgeEffect();
    }

    /**
     * Create an instance of {@link ExtractAction }
     * 
     */
    public ExtractAction createExtractAction() {
        return new ExtractAction();
    }

    /**
     * Create an instance of {@link DispelBuffCounterAtkEffect }
     * 
     */
    public DispelBuffCounterAtkEffect createDispelBuffCounterAtkEffect() {
        return new DispelBuffCounterAtkEffect();
    }

    /**
     * Create an instance of {@link ProcMPHealInstantEffect }
     * 
     */
    public ProcMPHealInstantEffect createProcMPHealInstantEffect() {
        return new ProcMPHealInstantEffect();
    }

    /**
     * Create an instance of {@link FpAttackInstantEffect }
     * 
     */
    public FpAttackInstantEffect createFpAttackInstantEffect() {
        return new FpAttackInstantEffect();
    }

    /**
     * Create an instance of {@link FearEffect }
     * 
     */
    public FearEffect createFearEffect() {
        return new FearEffect();
    }

    /**
     * Create an instance of {@link BleedEffect }
     * 
     */
    public BleedEffect createBleedEffect() {
        return new BleedEffect();
    }

    /**
     * Create an instance of {@link MeanModifier }
     * 
     */
    public MeanModifier createMeanModifier() {
        return new MeanModifier();
    }

    /**
     * Create an instance of {@link ChargeCondition }
     * 
     */
    public ChargeCondition createChargeCondition() {
        return new ChargeCondition();
    }

    /**
     * Create an instance of {@link DPHealInstantEffect }
     * 
     */
    public DPHealInstantEffect createDPHealInstantEffect() {
        return new DPHealInstantEffect();
    }

    /**
     * Create an instance of {@link SummonTotemEffect }
     * 
     */
    public SummonTotemEffect createSummonTotemEffect() {
        return new SummonTotemEffect();
    }

    /**
     * Create an instance of {@link TradeinList }
     * 
     */
    public TradeinList createTradeinList() {
        return new TradeinList();
    }

    /**
     * Create an instance of {@link HiPassEffect }
     * 
     */
    public HiPassEffect createHiPassEffect() {
        return new HiPassEffect();
    }

    /**
     * Create an instance of {@link ProcVPHealInstantEffect }
     * 
     */
    public ProcVPHealInstantEffect createProcVPHealInstantEffect() {
        return new ProcVPHealInstantEffect();
    }

    /**
     * Create an instance of {@link NoFPConsumEffect }
     * 
     */
    public NoFPConsumEffect createNoFPConsumEffect() {
        return new NoFPConsumEffect();
    }

    /**
     * Create an instance of {@link Improvement }
     * 
     */
    public Improvement createImprovement() {
        return new Improvement();
    }

    /**
     * Create an instance of {@link SelfFlyingCondition }
     * 
     */
    public SelfFlyingCondition createSelfFlyingCondition() {
        return new SelfFlyingCondition();
    }

    /**
     * Create an instance of {@link SnareEffect }
     * 
     */
    public SnareEffect createSnareEffect() {
        return new SnareEffect();
    }

    /**
     * Create an instance of {@link Modifier }
     * 
     */
    public Modifier createModifier() {
        return new Modifier();
    }

    /**
     * Create an instance of {@link FrontDamageModifier }
     * 
     */
    public FrontDamageModifier createFrontDamageModifier() {
        return new FrontDamageModifier();
    }

    /**
     * Create an instance of {@link SleepEffect }
     * 
     */
    public SleepEffect createSleepEffect() {
        return new SleepEffect();
    }

    /**
     * Create an instance of {@link BoostHateEffect }
     * 
     */
    public BoostHateEffect createBoostHateEffect() {
        return new BoostHateEffect();
    }

    /**
     * Create an instance of {@link BuffStunEffect }
     * 
     */
    public BuffStunEffect createBuffStunEffect() {
        return new BuffStunEffect();
    }

    /**
     * Create an instance of {@link SummonHomingEffect }
     * 
     */
    public SummonHomingEffect createSummonHomingEffect() {
        return new SummonHomingEffect();
    }

    /**
     * Create an instance of {@link NoResurrectPenaltyEffect }
     * 
     */
    public NoResurrectPenaltyEffect createNoResurrectPenaltyEffect() {
        return new NoResurrectPenaltyEffect();
    }

    /**
     * Create an instance of {@link ToyPetSpawnAction }
     * 
     */
    public ToyPetSpawnAction createToyPetSpawnAction() {
        return new ToyPetSpawnAction();
    }

    /**
     * Create an instance of {@link ShieldMasteryEffect }
     * 
     */
    public ShieldMasteryEffect createShieldMasteryEffect() {
        return new ShieldMasteryEffect();
    }

    /**
     * Create an instance of {@link XPBoostEffect }
     * 
     */
    public XPBoostEffect createXPBoostEffect() {
        return new XPBoostEffect();
    }

    /**
     * Create an instance of {@link MpCondition }
     * 
     */
    public MpCondition createMpCondition() {
        return new MpCondition();
    }

    /**
     * Create an instance of {@link ChainCondition }
     * 
     */
    public ChainCondition createChainCondition() {
        return new ChainCondition();
    }

    /**
     * Create an instance of {@link HpUsePeriodicAction }
     * 
     */
    public HpUsePeriodicAction createHpUsePeriodicAction() {
        return new HpUsePeriodicAction();
    }

    /**
     * Create an instance of {@link SummonSkillAreaEffect }
     * 
     */
    public SummonSkillAreaEffect createSummonSkillAreaEffect() {
        return new SummonSkillAreaEffect();
    }

    /**
     * Create an instance of {@link ShieldEffect }
     * 
     */
    public ShieldEffect createShieldEffect() {
        return new ShieldEffect();
    }

    /**
     * Create an instance of {@link OpenAerialEffect }
     * 
     */
    public OpenAerialEffect createOpenAerialEffect() {
        return new OpenAerialEffect();
    }

    /**
     * Create an instance of {@link CurseEffect }
     * 
     */
    public CurseEffect createCurseEffect() {
        return new CurseEffect();
    }

    /**
     * Create an instance of {@link HealCastorOnAttackedEffect }
     * 
     */
    public HealCastorOnAttackedEffect createHealCastorOnAttackedEffect() {
        return new HealCastorOnAttackedEffect();
    }

    /**
     * Create an instance of {@link DispelBuffEffect }
     * 
     */
    public DispelBuffEffect createDispelBuffEffect() {
        return new DispelBuffEffect();
    }

    /**
     * Create an instance of {@link SkillTree }
     * 
     */
    public SkillTree createSkillTree() {
        return new SkillTree();
    }

    /**
     * Create an instance of {@link Godstone }
     * 
     */
    public Godstone createGodstone() {
        return new Godstone();
    }

    /**
     * Create an instance of {@link ResurrectPositionalEffect }
     * 
     */
    public ResurrectPositionalEffect createResurrectPositionalEffect() {
        return new ResurrectPositionalEffect();
    }

    /**
     * Create an instance of {@link SanctuaryEffect }
     * 
     */
    public SanctuaryEffect createSanctuaryEffect() {
        return new SanctuaryEffect();
    }

    /**
     * Create an instance of {@link SwitchHostileEffect }
     * 
     */
    public SwitchHostileEffect createSwitchHostileEffect() {
        return new SwitchHostileEffect();
    }

    /**
     * Create an instance of {@link ProcAtkInstantEffect }
     * 
     */
    public ProcAtkInstantEffect createProcAtkInstantEffect() {
        return new ProcAtkInstantEffect();
    }

    /**
     * Create an instance of {@link DispelNpcDebuffEffect }
     * 
     */
    public DispelNpcDebuffEffect createDispelNpcDebuffEffect() {
        return new DispelNpcDebuffEffect();
    }

    /**
     * Create an instance of {@link ItemActions }
     * 
     */
    public ItemActions createItemActions() {
        return new ItemActions();
    }

    /**
     * Create an instance of {@link HealEffect }
     * 
     */
    public HealEffect createHealEffect() {
        return new HealEffect();
    }

    /**
     * Create an instance of {@link SkillData }
     * 
     */
    public SkillData createSkillData() {
        return new SkillData();
    }

    /**
     * Create an instance of {@link ArmorMasteryEffect }
     * 
     */
    public ArmorMasteryEffect createArmorMasteryEffect() {
        return new ArmorMasteryEffect();
    }

    /**
     * Create an instance of {@link ResurrectEffect }
     * 
     */
    public ResurrectEffect createResurrectEffect() {
        return new ResurrectEffect();
    }

    /**
     * Create an instance of {@link ReflectorEffect }
     * 
     */
    public ReflectorEffect createReflectorEffect() {
        return new ReflectorEffect();
    }

    /**
     * Create an instance of {@link NoReduceSpellATKInstantEffect }
     * 
     */
    public NoReduceSpellATKInstantEffect createNoReduceSpellATKInstantEffect() {
        return new NoReduceSpellATKInstantEffect();
    }

    /**
     * Create an instance of {@link HealInstantEffect }
     * 
     */
    public HealInstantEffect createHealInstantEffect() {
        return new HealInstantEffect();
    }

    /**
     * Create an instance of {@link PeriodicActions }
     * 
     */
    public PeriodicActions createPeriodicActions() {
        return new PeriodicActions();
    }

    /**
     * Create an instance of {@link DelayedFpAtkInstantEffect }
     * 
     */
    public DelayedFpAtkInstantEffect createDelayedFpAtkInstantEffect() {
        return new DelayedFpAtkInstantEffect();
    }

    /**
     * Create an instance of {@link BoostHealEffect }
     * 
     */
    public BoostHealEffect createBoostHealEffect() {
        return new BoostHealEffect();
    }

    /**
     * Create an instance of {@link AssembledItem }
     * 
     */
    public AssembledItem createAssembledItem() {
        return new AssembledItem();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link SkillLearnAction }
     * 
     */
    public SkillLearnAction createSkillLearnAction() {
        return new SkillLearnAction();
    }

    /**
     * Create an instance of {@link MpAttackInstantEffect }
     * 
     */
    public MpAttackInstantEffect createMpAttackInstantEffect() {
        return new MpAttackInstantEffect();
    }

    /**
     * Create an instance of {@link SummonHouseGateEffect }
     * 
     */
    public SummonHouseGateEffect createSummonHouseGateEffect() {
        return new SummonHouseGateEffect();
    }

    /**
     * Create an instance of {@link SilenceEffect }
     * 
     */
    public SilenceEffect createSilenceEffect() {
        return new SilenceEffect();
    }

    /**
     * Create an instance of {@link DecorateAction }
     * 
     */
    public DecorateAction createDecorateAction() {
        return new DecorateAction();
    }

    /**
     * Create an instance of {@link HideEffect }
     * 
     */
    public HideEffect createHideEffect() {
        return new HideEffect();
    }

    /**
     * Create an instance of {@link ProvokerEffect }
     * 
     */
    public ProvokerEffect createProvokerEffect() {
        return new ProvokerEffect();
    }

    /**
     * Create an instance of {@link StatboostEffect }
     * 
     */
    public StatboostEffect createStatboostEffect() {
        return new StatboostEffect();
    }

    /**
     * Create an instance of {@link SkillUseAction }
     * 
     */
    public SkillUseAction createSkillUseAction() {
        return new SkillUseAction();
    }

    /**
     * Create an instance of {@link BuffSleepEffect }
     * 
     */
    public BuffSleepEffect createBuffSleepEffect() {
        return new BuffSleepEffect();
    }

    /**
     * Create an instance of {@link Motion }
     * 
     */
    public Motion createMotion() {
        return new Motion();
    }

    /**
     * Create an instance of {@link SpellAttackEffect }
     * 
     */
    public SpellAttackEffect createSpellAttackEffect() {
        return new SpellAttackEffect();
    }

    /**
     * Create an instance of {@link WeaponMasteryEffect }
     * 
     */
    public WeaponMasteryEffect createWeaponMasteryEffect() {
        return new WeaponMasteryEffect();
    }

    /**
     * Create an instance of {@link ConfuseEffect }
     * 
     */
    public ConfuseEffect createConfuseEffect() {
        return new ConfuseEffect();
    }

    /**
     * Create an instance of {@link WeaponStatboostEffect }
     * 
     */
    public WeaponStatboostEffect createWeaponStatboostEffect() {
        return new WeaponStatboostEffect();
    }

    /**
     * Create an instance of {@link BackDashEffect }
     * 
     */
    public BackDashEffect createBackDashEffect() {
        return new BackDashEffect();
    }

    /**
     * Create an instance of {@link HpUseAction }
     * 
     */
    public HpUseAction createHpUseAction() {
        return new HpUseAction();
    }

    /**
     * Create an instance of {@link SummonEffect }
     * 
     */
    public SummonEffect createSummonEffect() {
        return new SummonEffect();
    }

    /**
     * Create an instance of {@link NoFlyEffect }
     * 
     */
    public NoFlyEffect createNoFlyEffect() {
        return new NoFlyEffect();
    }

    /**
     * Create an instance of {@link SummonHouseObjectAction }
     * 
     */
    public SummonHouseObjectAction createSummonHouseObjectAction() {
        return new SummonHouseObjectAction();
    }

    /**
     * Create an instance of {@link Acquisition }
     * 
     */
    public Acquisition createAcquisition() {
        return new Acquisition();
    }

    /**
     * Create an instance of {@link RecallInstantEffect }
     * 
     */
    public RecallInstantEffect createRecallInstantEffect() {
        return new RecallInstantEffect();
    }

    /**
     * Create an instance of {@link ActionModifiers }
     * 
     */
    public ActionModifiers createActionModifiers() {
        return new ActionModifiers();
    }

    /**
     * Create an instance of {@link SpellAttackInstantEffect }
     * 
     */
    public SpellAttackInstantEffect createSpellAttackInstantEffect() {
        return new SpellAttackInstantEffect();
    }

    /**
     * Create an instance of {@link BoostSkillCostEffect }
     * 
     */
    public BoostSkillCostEffect createBoostSkillCostEffect() {
        return new BoostSkillCostEffect();
    }

    /**
     * Create an instance of {@link ReturnPointEffect }
     * 
     */
    public ReturnPointEffect createReturnPointEffect() {
        return new ReturnPointEffect();
    }

    /**
     * Create an instance of {@link TitleAddAction }
     * 
     */
    public TitleAddAction createTitleAddAction() {
        return new TitleAddAction();
    }

    /**
     * Create an instance of {@link PoisonEffect }
     * 
     */
    public PoisonEffect createPoisonEffect() {
        return new PoisonEffect();
    }

    /**
     * Create an instance of {@link DispelDebuffEffect }
     * 
     */
    public DispelDebuffEffect createDispelDebuffEffect() {
        return new DispelDebuffEffect();
    }

    /**
     * Create an instance of {@link MpAttackEffect }
     * 
     */
    public MpAttackEffect createMpAttackEffect() {
        return new MpAttackEffect();
    }

    /**
     * Create an instance of {@link DpCondition }
     * 
     */
    public DpCondition createDpCondition() {
        return new DpCondition();
    }

    /**
     * Create an instance of {@link SignetEffect }
     * 
     */
    public SignetEffect createSignetEffect() {
        return new SignetEffect();
    }

    /**
     * Create an instance of {@link StunEffect }
     * 
     */
    public StunEffect createStunEffect() {
        return new StunEffect();
    }

    /**
     * Create an instance of {@link BackCondition }
     * 
     */
    public BackCondition createBackCondition() {
        return new BackCondition();
    }

    /**
     * Create an instance of {@link ExtendAuraRangeEffect }
     * 
     */
    public ExtendAuraRangeEffect createExtendAuraRangeEffect() {
        return new ExtendAuraRangeEffect();
    }

    /**
     * Create an instance of {@link FPHealEffect }
     * 
     */
    public FPHealEffect createFPHealEffect() {
        return new FPHealEffect();
    }

    /**
     * Create an instance of {@link DPTransferEffect }
     * 
     */
    public DPTransferEffect createDPTransferEffect() {
        return new DPTransferEffect();
    }

    /**
     * Create an instance of {@link FormCondition }
     * 
     */
    public FormCondition createFormCondition() {
        return new FormCondition();
    }

    /**
     * Create an instance of {@link DelayedSkillEffect }
     * 
     */
    public DelayedSkillEffect createDelayedSkillEffect() {
        return new DelayedSkillEffect();
    }

    /**
     * Create an instance of {@link BackDamageModifier }
     * 
     */
    public BackDamageModifier createBackDamageModifier() {
        return new BackDamageModifier();
    }

    /**
     * Create an instance of {@link OnFlyCondition }
     * 
     */
    public OnFlyCondition createOnFlyCondition() {
        return new OnFlyCondition();
    }

    /**
     * Create an instance of {@link UseLimits }
     * 
     */
    public UseLimits createUseLimits() {
        return new UseLimits();
    }

    /**
     * Create an instance of {@link PlayerMovedCondition }
     * 
     */
    public PlayerMovedCondition createPlayerMovedCondition() {
        return new PlayerMovedCondition();
    }

    /**
     * Create an instance of {@link CondSkillLauncherEffect }
     * 
     */
    public CondSkillLauncherEffect createCondSkillLauncherEffect() {
        return new CondSkillLauncherEffect();
    }

    /**
     * Create an instance of {@link BoostSkillCastingTimeEffect }
     * 
     */
    public BoostSkillCastingTimeEffect createBoostSkillCastingTimeEffect() {
        return new BoostSkillCastingTimeEffect();
    }

    /**
     * Create an instance of {@link WeaponStatupEffect }
     * 
     */
    public WeaponStatupEffect createWeaponStatupEffect() {
        return new WeaponStatupEffect();
    }

    /**
     * Create an instance of {@link SkillAtkDrainInstantEffect }
     * 
     */
    public SkillAtkDrainInstantEffect createSkillAtkDrainInstantEffect() {
        return new SkillAtkDrainInstantEffect();
    }

    /**
     * Create an instance of {@link OneTimeBoostSkillCriticalEffect }
     * 
     */
    public OneTimeBoostSkillCriticalEffect createOneTimeBoostSkillCriticalEffect() {
        return new OneTimeBoostSkillCriticalEffect();
    }

    /**
     * Create an instance of {@link DeformEffect }
     * 
     */
    public DeformEffect createDeformEffect() {
        return new DeformEffect();
    }

    /**
     * Create an instance of {@link DPHealEffect }
     * 
     */
    public DPHealEffect createDPHealEffect() {
        return new DPHealEffect();
    }

    /**
     * Create an instance of {@link ProcFPHealInstantEffect }
     * 
     */
    public ProcFPHealInstantEffect createProcFPHealInstantEffect() {
        return new ProcFPHealInstantEffect();
    }

    /**
     * Create an instance of {@link SkillAttackInstantEffect }
     * 
     */
    public SkillAttackInstantEffect createSkillAttackInstantEffect() {
        return new SkillAttackInstantEffect();
    }

    /**
     * Create an instance of {@link SlowEffect }
     * 
     */
    public SlowEffect createSlowEffect() {
        return new SlowEffect();
    }

    /**
     * Create an instance of {@link Effects }
     * 
     */
    public Effects createEffects() {
        return new Effects();
    }

    /**
     * Create an instance of {@link SimpleRootEffect }
     * 
     */
    public SimpleRootEffect createSimpleRootEffect() {
        return new SimpleRootEffect();
    }

    /**
     * Create an instance of {@link CraftLearnAction }
     * 
     */
    public CraftLearnAction createCraftLearnAction() {
        return new CraftLearnAction();
    }

    /**
     * Create an instance of {@link TargetCondition }
     * 
     */
    public TargetCondition createTargetCondition() {
        return new TargetCondition();
    }

    /**
     * Create an instance of {@link StumbleEffect }
     * 
     */
    public StumbleEffect createStumbleEffect() {
        return new StumbleEffect();
    }

    /**
     * Create an instance of {@link RebirthEffect }
     * 
     */
    public RebirthEffect createRebirthEffect() {
        return new RebirthEffect();
    }

    /**
     * Create an instance of {@link ChargeAction }
     * 
     */
    public ChargeAction createChargeAction() {
        return new ChargeAction();
    }

    /**
     * Create an instance of {@link StatupEffect }
     * 
     */
    public StatupEffect createStatupEffect() {
        return new StatupEffect();
    }

    /**
     * Create an instance of {@link MPHealEffect }
     * 
     */
    public MPHealEffect createMPHealEffect() {
        return new MPHealEffect();
    }

    /**
     * Create an instance of {@link CaseHealEffect }
     * 
     */
    public CaseHealEffect createCaseHealEffect() {
        return new CaseHealEffect();
    }

    /**
     * Create an instance of {@link DispelDebuffMentalEffect }
     * 
     */
    public DispelDebuffMentalEffect createDispelDebuffMentalEffect() {
        return new DispelDebuffMentalEffect();
    }

    /**
     * Create an instance of {@link RandomMoveLocEffect }
     * 
     */
    public RandomMoveLocEffect createRandomMoveLocEffect() {
        return new RandomMoveLocEffect();
    }

    /**
     * Create an instance of {@link SpellAtkDrainInstantEffect }
     * 
     */
    public SpellAtkDrainInstantEffect createSpellAtkDrainInstantEffect() {
        return new SpellAtkDrainInstantEffect();
    }

    /**
     * Create an instance of {@link RootEffect }
     * 
     */
    public RootEffect createRootEffect() {
        return new RootEffect();
    }

    /**
     * Create an instance of {@link DeathBlowEffect }
     * 
     */
    public DeathBlowEffect createDeathBlowEffect() {
        return new DeathBlowEffect();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link QuestStartAction }
     * 
     */
    public QuestStartAction createQuestStartAction() {
        return new QuestStartAction();
    }

    /**
     * Create an instance of {@link ProcDPHealInstantEffect }
     * 
     */
    public ProcDPHealInstantEffect createProcDPHealInstantEffect() {
        return new ProcDPHealInstantEffect();
    }

    /**
     * Create an instance of {@link BindEffect }
     * 
     */
    public BindEffect createBindEffect() {
        return new BindEffect();
    }

    /**
     * Create an instance of {@link NoDeathPenaltyEffect }
     * 
     */
    public NoDeathPenaltyEffect createNoDeathPenaltyEffect() {
        return new NoDeathPenaltyEffect();
    }

    /**
     * Create an instance of {@link FPHealInstantEffect }
     * 
     */
    public FPHealInstantEffect createFPHealInstantEffect() {
        return new FPHealInstantEffect();
    }

    /**
     * Create an instance of {@link SummonGroupGateEffect }
     * 
     */
    public SummonGroupGateEffect createSummonGroupGateEffect() {
        return new SummonGroupGateEffect();
    }

    /**
     * Create an instance of {@link CloseAerialEffect }
     * 
     */
    public CloseAerialEffect createCloseAerialEffect() {
        return new CloseAerialEffect();
    }

    /**
     * Create an instance of {@link AlwaysResistEffect }
     * 
     */
    public AlwaysResistEffect createAlwaysResistEffect() {
        return new AlwaysResistEffect();
    }

    /**
     * Create an instance of {@link MpUseAction }
     * 
     */
    public MpUseAction createMpUseAction() {
        return new MpUseAction();
    }

    /**
     * Create an instance of {@link FallEffect }
     * 
     */
    public FallEffect createFallEffect() {
        return new FallEffect();
    }

    /**
     * Create an instance of {@link AssemblyItemAction }
     * 
     */
    public AssemblyItemAction createAssemblyItemAction() {
        return new AssemblyItemAction();
    }

    /**
     * Create an instance of {@link ToyPetAdoptAction }
     * 
     */
    public ToyPetAdoptAction createToyPetAdoptAction() {
        return new ToyPetAdoptAction();
    }

    /**
     * Create an instance of {@link InstanceTimeClear }
     * 
     */
    public InstanceTimeClear createInstanceTimeClear() {
        return new InstanceTimeClear();
    }

    /**
     * Create an instance of {@link ExpandInventoryAction }
     * 
     */
    public ExpandInventoryAction createExpandInventoryAction() {
        return new ExpandInventoryAction();
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link CombatCheckCondition }
     * 
     */
    public CombatCheckCondition createCombatCheckCondition() {
        return new CombatCheckCondition();
    }

    /**
     * Create an instance of {@link WeaponDualEffect }
     * 
     */
    public WeaponDualEffect createWeaponDualEffect() {
        return new WeaponDualEffect();
    }

    /**
     * Create an instance of {@link PetOrderUseUltraSkillEffect }
     * 
     */
    public PetOrderUseUltraSkillEffect createPetOrderUseUltraSkillEffect() {
        return new PetOrderUseUltraSkillEffect();
    }

    /**
     * Create an instance of {@link Modifiers }
     * 
     */
    public Modifiers createModifiers() {
        return new Modifiers();
    }

    /**
     * Create an instance of {@link InvulnerableWingEffect }
     * 
     */
    public InvulnerableWingEffect createInvulnerableWingEffect() {
        return new InvulnerableWingEffect();
    }

    /**
     * Create an instance of {@link DispelDebuffPhysicalEffect }
     * 
     */
    public DispelDebuffPhysicalEffect createDispelDebuffPhysicalEffect() {
        return new DispelDebuffPhysicalEffect();
    }

    /**
     * Create an instance of {@link HostileUpEffect }
     * 
     */
    public HostileUpEffect createHostileUpEffect() {
        return new HostileUpEffect();
    }

    /**
     * Create an instance of {@link ShapeChangeEffect }
     * 
     */
    public ShapeChangeEffect createShapeChangeEffect() {
        return new ShapeChangeEffect();
    }

    /**
     * Create an instance of {@link ItemTemplate }
     * 
     */
    public ItemTemplate createItemTemplate() {
        return new ItemTemplate();
    }

    /**
     * Create an instance of {@link RideAction }
     * 
     */
    public RideAction createRideAction() {
        return new RideAction();
    }

    /**
     * Create an instance of {@link EvadeEffect }
     * 
     */
    public EvadeEffect createEvadeEffect() {
        return new EvadeEffect();
    }

    /**
     * Create an instance of {@link DispelNpcBuffEffect }
     * 
     */
    public DispelNpcBuffEffect createDispelNpcBuffEffect() {
        return new DispelNpcBuffEffect();
    }

    /**
     * Create an instance of {@link AbnormalDamageModifier }
     * 
     */
    public AbnormalDamageModifier createAbnormalDamageModifier() {
        return new AbnormalDamageModifier();
    }

    /**
     * Create an instance of {@link BoostSpellAttackEffect }
     * 
     */
    public BoostSpellAttackEffect createBoostSpellAttackEffect() {
        return new BoostSpellAttackEffect();
    }

    /**
     * Create an instance of {@link SignetBurstEffect }
     * 
     */
    public SignetBurstEffect createSignetBurstEffect() {
        return new SignetBurstEffect();
    }

    /**
     * Create an instance of {@link ArrowCheckCondition }
     * 
     */
    public ArrowCheckCondition createArrowCheckCondition() {
        return new ArrowCheckCondition();
    }

    /**
     * Create an instance of {@link SkillTreeEntry }
     * 
     */
    public SkillTreeEntry createSkillTreeEntry() {
        return new SkillTreeEntry();
    }

    /**
     * Create an instance of {@link AbnormalStateCondition }
     * 
     */
    public AbnormalStateCondition createAbnormalStateCondition() {
        return new AbnormalStateCondition();
    }

    /**
     * Create an instance of {@link CarveSignetEffect }
     * 
     */
    public CarveSignetEffect createCarveSignetEffect() {
        return new CarveSignetEffect();
    }

    /**
     * Create an instance of {@link ParalyzeEffect }
     * 
     */
    public ParalyzeEffect createParalyzeEffect() {
        return new ParalyzeEffect();
    }

    /**
     * Create an instance of {@link Stigma }
     * 
     */
    public Stigma createStigma() {
        return new Stigma();
    }

    /**
     * Create an instance of {@link ItemUseAction }
     * 
     */
    public ItemUseAction createItemUseAction() {
        return new ItemUseAction();
    }

    /**
     * Create an instance of {@link AbstractDispelEffect }
     * 
     */
    public AbstractDispelEffect createAbstractDispelEffect() {
        return new AbstractDispelEffect();
    }

    /**
     * Create an instance of {@link ArmorCondition }
     * 
     */
    public ArmorCondition createArmorCondition() {
        return new ArmorCondition();
    }

    /**
     * Create an instance of {@link CosmeticItemAction }
     * 
     */
    public CosmeticItemAction createCosmeticItemAction() {
        return new CosmeticItemAction();
    }

    /**
     * Create an instance of {@link BlindEffect }
     * 
     */
    public BlindEffect createBlindEffect() {
        return new BlindEffect();
    }

    /**
     * Create an instance of {@link SummonServantEffect }
     * 
     */
    public SummonServantEffect createSummonServantEffect() {
        return new SummonServantEffect();
    }

    /**
     * Create an instance of {@link ResurrectBaseEffect }
     * 
     */
    public ResurrectBaseEffect createResurrectBaseEffect() {
        return new ResurrectBaseEffect();
    }

    /**
     * Create an instance of {@link DecomposeAction }
     * 
     */
    public DecomposeAction createDecomposeAction() {
        return new DecomposeAction();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link DiseaseEffect }
     * 
     */
    public DiseaseEffect createDiseaseEffect() {
        return new DiseaseEffect();
    }

    /**
     * Create an instance of {@link MagicCounterAtkEffect }
     * 
     */
    public MagicCounterAtkEffect createMagicCounterAtkEffect() {
        return new MagicCounterAtkEffect();
    }

    /**
     * Create an instance of {@link SubEffect }
     * 
     */
    public SubEffect createSubEffect() {
        return new SubEffect();
    }

    /**
     * Create an instance of {@link WeaponCondition }
     * 
     */
    public WeaponCondition createWeaponCondition() {
        return new WeaponCondition();
    }

    /**
     * Create an instance of {@link ChangeHateOnAttackedEffect }
     * 
     */
    public ChangeHateOnAttackedEffect createChangeHateOnAttackedEffect() {
        return new ChangeHateOnAttackedEffect();
    }

    /**
     * Create an instance of {@link DashEffect }
     * 
     */
    public DashEffect createDashEffect() {
        return new DashEffect();
    }

    /**
     * Create an instance of {@link ProtectEffect }
     * 
     */
    public ProtectEffect createProtectEffect() {
        return new ProtectEffect();
    }

    /**
     * Create an instance of {@link TargetFlyingCondition }
     * 
     */
    public TargetFlyingCondition createTargetFlyingCondition() {
        return new TargetFlyingCondition();
    }

    /**
     * Create an instance of {@link HealCastorOnTargetDeadEffect }
     * 
     */
    public HealCastorOnTargetDeadEffect createHealCastorOnTargetDeadEffect() {
        return new HealCastorOnTargetDeadEffect();
    }

    /**
     * Create an instance of {@link PulledEffect }
     * 
     */
    public PulledEffect createPulledEffect() {
        return new PulledEffect();
    }

    /**
     * Create an instance of {@link TradeinItem }
     * 
     */
    public TradeinItem createTradeinItem() {
        return new TradeinItem();
    }

    /**
     * Create an instance of {@link SkillLauncherEffect }
     * 
     */
    public SkillLauncherEffect createSkillLauncherEffect() {
        return new SkillLauncherEffect();
    }

    /**
     * Create an instance of {@link RequireSkill }
     * 
     */
    public RequireSkill createRequireSkill() {
        return new RequireSkill();
    }

    /**
     * Create an instance of {@link DyeAction }
     * 
     */
    public DyeAction createDyeAction() {
        return new DyeAction();
    }

    /**
     * Create an instance of {@link SpinEffect }
     * 
     */
    public SpinEffect createSpinEffect() {
        return new SpinEffect();
    }

    /**
     * Create an instance of {@link SearchEffect }
     * 
     */
    public SearchEffect createSearchEffect() {
        return new SearchEffect();
    }

    /**
     * Create an instance of {@link DelayedSpellAttackInstantEffect }
     * 
     */
    public DelayedSpellAttackInstantEffect createDelayedSpellAttackInstantEffect() {
        return new DelayedSpellAttackInstantEffect();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleModifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sub", scope = Modifiers.class)
    public JAXBElement<SimpleModifier> createModifiersSub(SimpleModifier value) {
        return new JAXBElement<SimpleModifier>(_ModifiersSub_QNAME, SimpleModifier.class, Modifiers.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleModifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rate", scope = Modifiers.class)
    public JAXBElement<SimpleModifier> createModifiersRate(SimpleModifier value) {
        return new JAXBElement<SimpleModifier>(_ModifiersRate_QNAME, SimpleModifier.class, Modifiers.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleModifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "set", scope = Modifiers.class)
    public JAXBElement<SimpleModifier> createModifiersSet(SimpleModifier value) {
        return new JAXBElement<SimpleModifier>(_ModifiersSet_QNAME, SimpleModifier.class, Modifiers.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeanModifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mean", scope = Modifiers.class)
    public JAXBElement<MeanModifier> createModifiersMean(MeanModifier value) {
        return new JAXBElement<MeanModifier>(_ModifiersMean_QNAME, MeanModifier.class, Modifiers.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleModifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "add", scope = Modifiers.class)
    public JAXBElement<SimpleModifier> createModifiersAdd(SimpleModifier value) {
        return new JAXBElement<SimpleModifier>(_ModifiersAdd_QNAME, SimpleModifier.class, Modifiers.class, value);
    }

}
