//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PeriodicActions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PeriodicActions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="hpuse" type="{}HpUsePeriodicAction" minOccurs="0"/>
 *         &lt;element name="mpuse" type="{}MpUsePeriodicAction" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="checktime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PeriodicActions", propOrder = {
    "hpuseAndMpuse"
})
public class PeriodicActions {

    @XmlElements({
        @XmlElement(name = "hpuse", type = HpUsePeriodicAction.class),
        @XmlElement(name = "mpuse", type = MpUsePeriodicAction.class)
    })
    protected List<PeriodicAction> hpuseAndMpuse;
    @XmlAttribute
    protected Integer checktime;

    /**
     * Gets the value of the hpuseAndMpuse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hpuseAndMpuse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHpuseAndMpuse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HpUsePeriodicAction }
     * {@link MpUsePeriodicAction }
     * 
     * 
     */
    public List<PeriodicAction> getHpuseAndMpuse() {
        if (hpuseAndMpuse == null) {
            hpuseAndMpuse = new ArrayList<PeriodicAction>();
        }
        return this.hpuseAndMpuse;
    }

    /**
     * Gets the value of the checktime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getChecktime() {
        return checktime;
    }

    /**
     * Sets the value of the checktime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setChecktime(Integer value) {
        this.checktime = value;
    }

}
