//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for playerClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="playerClass">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="WARRIOR"/>
 *     &lt;enumeration value="GLADIATOR"/>
 *     &lt;enumeration value="TEMPLAR"/>
 *     &lt;enumeration value="SCOUT"/>
 *     &lt;enumeration value="ASSASSIN"/>
 *     &lt;enumeration value="RANGER"/>
 *     &lt;enumeration value="MAGE"/>
 *     &lt;enumeration value="SORCERER"/>
 *     &lt;enumeration value="SPIRIT_MASTER"/>
 *     &lt;enumeration value="PRIEST"/>
 *     &lt;enumeration value="CLERIC"/>
 *     &lt;enumeration value="CHANTER"/>
 *     &lt;enumeration value="ENGINEER"/>
 *     &lt;enumeration value="ARTIST"/>
 *     &lt;enumeration value="GUNNER"/>
 *     &lt;enumeration value="RIDER"/>
 *     &lt;enumeration value="BARD"/>
 *     &lt;enumeration value="ALL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "playerClass")
@XmlEnum
public enum PlayerClass {

    WARRIOR,
    GLADIATOR,
    TEMPLAR,
    SCOUT,
    ASSASSIN,
    RANGER,
    MAGE,
    SORCERER,
    SPIRIT_MASTER,
    PRIEST,
    CLERIC,
    CHANTER,
    ENGINEER,
    ARTIST,
    GUNNER,
    RIDER,
    BARD,
    ALL;

    public String value() {
        return name();
    }

    public static PlayerClass fromValue(String v) {
        return valueOf(v);
    }

}
