//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Race.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Race">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ASMODIANS"/>
 *     &lt;enumeration value="BARRIER"/>
 *     &lt;enumeration value="BEAST"/>
 *     &lt;enumeration value="BROWNIE"/>
 *     &lt;enumeration value="CARRIER"/>
 *     &lt;enumeration value="CONSTRUCT"/>
 *     &lt;enumeration value="DEFORM"/>
 *     &lt;enumeration value="DEMIHUMANOID"/>
 *     &lt;enumeration value="DRAGON"/>
 *     &lt;enumeration value="DRAGON_CASTLE_DOOR"/>
 *     &lt;enumeration value="DRAKAN"/>
 *     &lt;enumeration value="ELEMENTAL"/>
 *     &lt;enumeration value="ELYOS"/>
 *     &lt;enumeration value="EVENT_TOWER_DARK"/>
 *     &lt;enumeration value="EVENT_TOWER_LIGHT"/>
 *     &lt;enumeration value="GCHIEF_DARK"/>
 *     &lt;enumeration value="GCHIEF_LIGHT"/>
 *     &lt;enumeration value="GHENCHMAN_DARK"/>
 *     &lt;enumeration value="GHENCHMAN_LIGHT"/>
 *     &lt;enumeration value="GOBLIN"/>
 *     &lt;enumeration value="KRALL"/>
 *     &lt;enumeration value="LIVINGWATER"/>
 *     &lt;enumeration value="LIZARDMAN"/>
 *     &lt;enumeration value="LYCAN"/>
 *     &lt;enumeration value="MAGICALMONSTER"/>
 *     &lt;enumeration value="NAGA"/>
 *     &lt;enumeration value="NEUT"/>
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="NPC"/>
 *     &lt;enumeration value="OUTSIDER"/>
 *     &lt;enumeration value="PC_ALL"/>
 *     &lt;enumeration value="PC_DARK_CASTLE_DOOR"/>
 *     &lt;enumeration value="PC_LIGHT_CASTLE_DOOR"/>
 *     &lt;enumeration value="RATMAN"/>
 *     &lt;enumeration value="SHULACK"/>
 *     &lt;enumeration value="TELEPORTER"/>
 *     &lt;enumeration value="TRICODARK"/>
 *     &lt;enumeration value="UNDEAD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Race")
@XmlEnum
public enum Race {

    ASMODIANS,
    BARRIER,
    BEAST,
    BROWNIE,
    CARRIER,
    CONSTRUCT,
    DEFORM,
    DEMIHUMANOID,
    DRAGON,
    DRAGON_CASTLE_DOOR,
    DRAKAN,
    ELEMENTAL,
    ELYOS,
    EVENT_TOWER_DARK,
    EVENT_TOWER_LIGHT,
    GCHIEF_DARK,
    GCHIEF_LIGHT,
    GHENCHMAN_DARK,
    GHENCHMAN_LIGHT,
    GOBLIN,
    KRALL,
    LIVINGWATER,
    LIZARDMAN,
    LYCAN,
    MAGICALMONSTER,
    NAGA,
    NEUT,
    NONE,
    NPC,
    OUTSIDER,
    PC_ALL,
    PC_DARK_CASTLE_DOOR,
    PC_LIGHT_CASTLE_DOOR,
    RATMAN,
    SHULACK,
    TELEPORTER,
    TRICODARK,
    UNDEAD;

    public String value() {
        return name();
    }

    public static Race fromValue(String v) {
        return valueOf(v);
    }

}
