//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShieldEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShieldEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}Effect">
 *       &lt;attribute name="percent" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hitdelta" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="hitvalue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="radius" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="minradius" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="condrace" type="{}Race" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShieldEffect")
@XmlSeeAlso({
    ConvertHealEffect.class,
    ReflectorEffect.class,
    ProvokerEffect.class,
    ProtectEffect.class
})
public class ShieldEffect
    extends Effect
{

    @XmlAttribute
    protected Boolean percent;
    @XmlAttribute
    protected Integer hitdelta;
    @XmlAttribute
    protected Integer hitvalue;
    @XmlAttribute
    protected Integer radius;
    @XmlAttribute
    protected Integer minradius;
    @XmlAttribute
    protected Race condrace;

    /**
     * Gets the value of the percent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPercent() {
        return percent;
    }

    /**
     * Sets the value of the percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPercent(Boolean value) {
        this.percent = value;
    }

    /**
     * Gets the value of the hitdelta property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHitdelta() {
        return hitdelta;
    }

    /**
     * Sets the value of the hitdelta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHitdelta(Integer value) {
        this.hitdelta = value;
    }

    /**
     * Gets the value of the hitvalue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHitvalue() {
        return hitvalue;
    }

    /**
     * Sets the value of the hitvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHitvalue(Integer value) {
        this.hitvalue = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRadius(Integer value) {
        this.radius = value;
    }

    /**
     * Gets the value of the minradius property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinradius() {
        return minradius;
    }

    /**
     * Sets the value of the minradius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinradius(Integer value) {
        this.minradius = value;
    }

    /**
     * Gets the value of the condrace property.
     * 
     * @return
     *     possible object is
     *     {@link Race }
     *     
     */
    public Race getCondrace() {
        return condrace;
    }

    /**
     * Sets the value of the condrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Race }
     *     
     */
    public void setCondrace(Race value) {
        this.condrace = value;
    }

}
