//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SkillAttackInstantEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkillAttackInstantEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}DamageEffect">
 *       &lt;attribute name="rnddmg" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cannotmiss" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkillAttackInstantEffect")
public class SkillAttackInstantEffect
    extends DamageEffect
{

    @XmlAttribute
    protected Integer rnddmg;
    @XmlAttribute
    protected Boolean cannotmiss;

    /**
     * Gets the value of the rnddmg property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRnddmg() {
        return rnddmg;
    }

    /**
     * Sets the value of the rnddmg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRnddmg(Integer value) {
        this.rnddmg = value;
    }

    /**
     * Gets the value of the cannotmiss property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getCannotmiss() {
        return cannotmiss;
    }

    /**
     * Sets the value of the cannotmiss property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCannotmiss(Boolean value) {
        this.cannotmiss = value;
    }

}
