//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SkillTreeEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkillTreeEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="classId" use="required" type="{}playerClass" />
 *       &lt;attribute name="skillId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="skillLevel" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="autolearn" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="stigma" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="race" use="required" type="{}Race" />
 *       &lt;attribute name="minLevel" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkillTreeEntry")
public class SkillTreeEntry {

    @XmlAttribute(required = true)
    protected PlayerClass classId;
    @XmlAttribute(required = true)
    protected int skillId;
    @XmlAttribute(required = true)
    protected int skillLevel;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected Boolean autolearn;
    @XmlAttribute
    protected Boolean stigma;
    @XmlAttribute(required = true)
    protected Race race;
    @XmlAttribute(required = true)
    protected int minLevel;

    /**
     * Gets the value of the classId property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerClass }
     *     
     */
    public PlayerClass getClassId() {
        return classId;
    }

    /**
     * Sets the value of the classId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerClass }
     *     
     */
    public void setClassId(PlayerClass value) {
        this.classId = value;
    }

    /**
     * Gets the value of the skillId property.
     * 
     */
    public int getSkillId() {
        return skillId;
    }

    /**
     * Sets the value of the skillId property.
     * 
     */
    public void setSkillId(int value) {
        this.skillId = value;
    }

    /**
     * Gets the value of the skillLevel property.
     * 
     */
    public int getSkillLevel() {
        return skillLevel;
    }

    /**
     * Sets the value of the skillLevel property.
     * 
     */
    public void setSkillLevel(int value) {
        this.skillLevel = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the autolearn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAutolearn() {
        return autolearn;
    }

    /**
     * Sets the value of the autolearn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutolearn(Boolean value) {
        this.autolearn = value;
    }

    /**
     * Gets the value of the stigma property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getStigma() {
        if (stigma == null) {
            return false;
        } else {
            return stigma;
        }
    }

    /**
     * Sets the value of the stigma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStigma(Boolean value) {
        this.stigma = value;
    }

    /**
     * Gets the value of the race property.
     * 
     * @return
     *     possible object is
     *     {@link Race }
     *     
     */
    public Race getRace() {
        return race;
    }

    /**
     * Sets the value of the race property.
     * 
     * @param value
     *     allowed object is
     *     {@link Race }
     *     
     */
    public void setRace(Race value) {
        this.race = value;
    }

    /**
     * Gets the value of the minLevel property.
     * 
     */
    public int getMinLevel() {
        return minLevel;
    }

    /**
     * Sets the value of the minLevel property.
     * 
     */
    public void setMinLevel(int value) {
        this.minLevel = value;
    }

}
