//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SkillTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkillTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" type="{}Properties" minOccurs="0"/>
 *         &lt;element name="startconditions" type="{}Conditions" minOccurs="0"/>
 *         &lt;element name="useconditions" type="{}Conditions" minOccurs="0"/>
 *         &lt;element name="useequipmentconditions" type="{}Conditions" minOccurs="0"/>
 *         &lt;element name="effects" type="{}Effects" minOccurs="0"/>
 *         &lt;element name="actions" type="{}Actions" minOccurs="0"/>
 *         &lt;element name="periodicactions" type="{}PeriodicActions" minOccurs="0"/>
 *         &lt;element name="motion" type="{}Motion" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="counter_skill" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="penalty_skill_id" type="{}skillId" />
 *       &lt;attribute name="skill_id" use="required" type="{}skillId" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nameId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="stack" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cooldownId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="lvl" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="skilltype" use="required" type="{}skillType" />
 *       &lt;attribute name="attacktype" type="{}attackType" />
 *       &lt;attribute name="skillsubtype" use="required" type="{}skillSubType" />
 *       &lt;attribute name="conflict_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="tslot" type="{}TargetSlot" />
 *       &lt;attribute name="tslot_level" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="dispel_category" type="{}DispelCategoryType" default="NONE" />
 *       &lt;attribute name="req_dispel_level" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="activation" use="required" type="{}activationAttribute" />
 *       &lt;attribute name="stigma" type="{}StigmaType" />
 *       &lt;attribute name="ammospeed" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cooldown" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="pvp_damage" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="pvp_duration" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="chain_skill_prob" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="cancel_rate" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="stance" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="skillset_exception" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="skillset_maxoccur" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="avatar" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ground" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="unpottable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="remove_flyend" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="noremoveatdie" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkillTemplate", propOrder = {
    "properties",
    "startconditions",
    "useconditions",
    "useequipmentconditions",
    "effects",
    "actions",
    "periodicactions",
    "motion"
})
public class SkillTemplate {

    protected Properties properties;
    protected Conditions startconditions;
    protected Conditions useconditions;
    protected Conditions useequipmentconditions;
    protected Effects effects;
    protected Actions actions;
    protected PeriodicActions periodicactions;
    protected Motion motion;
    @XmlAttribute(name = "counter_skill")
    protected String counterSkill;
    @XmlAttribute(name = "penalty_skill_id")
    protected Integer penaltySkillId;
    @XmlAttribute(name = "skill_id", required = true)
    protected int skillId;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected Integer nameId;
    @XmlAttribute
    protected String stack;
    @XmlAttribute
    protected Integer cooldownId;
    @XmlAttribute
    protected Integer lvl;
    @XmlAttribute(required = true)
    protected String skilltype;
    @XmlAttribute
    protected AttackType attacktype;
    @XmlAttribute(required = true)
    protected String skillsubtype;
    @XmlAttribute(name = "conflict_id")
    protected Integer conflictId;
    @XmlAttribute
    protected String tslot;
    @XmlAttribute(name = "tslot_level")
    protected Integer tslotLevel;
    @XmlAttribute(name = "dispel_category")
    protected String dispelCategory;
    @XmlAttribute(name = "req_dispel_level")
    protected Integer reqDispelLevel;
    @XmlAttribute(required = true)
    protected String activation;
    @XmlAttribute
    protected String stigma;
    @XmlAttribute
    protected Integer ammospeed;
    @XmlAttribute(required = true)
    protected int duration;
    @XmlAttribute
    protected Integer cooldown;
    @XmlAttribute(name = "pvp_damage")
    protected Integer pvpDamage;
    @XmlAttribute(name = "pvp_duration")
    protected Integer pvpDuration;
    @XmlAttribute(name = "chain_skill_prob")
    protected Integer chainSkillProb;
    @XmlAttribute(name = "cancel_rate")
    protected Integer cancelRate;
    @XmlAttribute
    protected Boolean stance;
    @XmlAttribute(name = "skillset_exception")
    protected Integer skillsetException;
    @XmlAttribute(name = "skillset_maxoccur")
    protected Integer skillsetMaxoccur;
    @XmlAttribute
    protected Boolean avatar;
    @XmlAttribute
    protected Boolean ground;
    @XmlAttribute
    protected Boolean unpottable;
    @XmlAttribute(name = "remove_flyend")
    protected Boolean removeFlyend;
    @XmlAttribute
    protected Boolean noremoveatdie;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the startconditions property.
     * 
     * @return
     *     possible object is
     *     {@link Conditions }
     *     
     */
    public Conditions getStartconditions() {
        return startconditions;
    }

    /**
     * Sets the value of the startconditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *     
     */
    public void setStartconditions(Conditions value) {
        this.startconditions = value;
    }

    /**
     * Gets the value of the useconditions property.
     * 
     * @return
     *     possible object is
     *     {@link Conditions }
     *     
     */
    public Conditions getUseconditions() {
        return useconditions;
    }

    /**
     * Sets the value of the useconditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *     
     */
    public void setUseconditions(Conditions value) {
        this.useconditions = value;
    }

    /**
     * Gets the value of the useequipmentconditions property.
     * 
     * @return
     *     possible object is
     *     {@link Conditions }
     *     
     */
    public Conditions getUseequipmentconditions() {
        return useequipmentconditions;
    }

    /**
     * Sets the value of the useequipmentconditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *     
     */
    public void setUseequipmentconditions(Conditions value) {
        this.useequipmentconditions = value;
    }

    /**
     * Gets the value of the effects property.
     * 
     * @return
     *     possible object is
     *     {@link Effects }
     *     
     */
    public Effects getEffects() {
        return effects;
    }

    /**
     * Sets the value of the effects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Effects }
     *     
     */
    public void setEffects(Effects value) {
        this.effects = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link Actions }
     *     
     */
    public Actions getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actions }
     *     
     */
    public void setActions(Actions value) {
        this.actions = value;
    }

    /**
     * Gets the value of the periodicactions property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodicActions }
     *     
     */
    public PeriodicActions getPeriodicactions() {
        return periodicactions;
    }

    /**
     * Sets the value of the periodicactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodicActions }
     *     
     */
    public void setPeriodicactions(PeriodicActions value) {
        this.periodicactions = value;
    }

    /**
     * Gets the value of the motion property.
     * 
     * @return
     *     possible object is
     *     {@link Motion }
     *     
     */
    public Motion getMotion() {
        return motion;
    }

    /**
     * Sets the value of the motion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Motion }
     *     
     */
    public void setMotion(Motion value) {
        this.motion = value;
    }

    /**
     * Gets the value of the counterSkill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounterSkill() {
        return counterSkill;
    }

    /**
     * Sets the value of the counterSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounterSkill(String value) {
        this.counterSkill = value;
    }

    /**
     * Gets the value of the penaltySkillId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPenaltySkillId() {
        return penaltySkillId;
    }

    /**
     * Sets the value of the penaltySkillId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPenaltySkillId(Integer value) {
        this.penaltySkillId = value;
    }

    /**
     * Gets the value of the skillId property.
     * 
     */
    public int getSkillId() {
        return skillId;
    }

    /**
     * Sets the value of the skillId property.
     * 
     */
    public void setSkillId(int value) {
        this.skillId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nameId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNameId() {
        return nameId;
    }

    /**
     * Sets the value of the nameId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNameId(Integer value) {
        this.nameId = value;
    }

    /**
     * Gets the value of the stack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStack() {
        return stack;
    }

    /**
     * Sets the value of the stack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStack(String value) {
        this.stack = value;
    }

    /**
     * Gets the value of the cooldownId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCooldownId() {
        return cooldownId;
    }

    /**
     * Sets the value of the cooldownId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCooldownId(Integer value) {
        this.cooldownId = value;
    }

    /**
     * Gets the value of the lvl property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLvl() {
        return lvl;
    }

    /**
     * Sets the value of the lvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLvl(Integer value) {
        this.lvl = value;
    }

    /**
     * Gets the value of the skilltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkilltype() {
        return skilltype;
    }

    /**
     * Sets the value of the skilltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkilltype(String value) {
        this.skilltype = value;
    }

    /**
     * Gets the value of the attacktype property.
     * 
     * @return
     *     possible object is
     *     {@link AttackType }
     *     
     */
    public AttackType getAttacktype() {
        return attacktype;
    }

    /**
     * Sets the value of the attacktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttackType }
     *     
     */
    public void setAttacktype(AttackType value) {
        this.attacktype = value;
    }

    /**
     * Gets the value of the skillsubtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkillsubtype() {
        return skillsubtype;
    }

    /**
     * Sets the value of the skillsubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkillsubtype(String value) {
        this.skillsubtype = value;
    }

    /**
     * Gets the value of the conflictId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConflictId() {
        return conflictId;
    }

    /**
     * Sets the value of the conflictId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConflictId(Integer value) {
        this.conflictId = value;
    }

    /**
     * Gets the value of the tslot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTslot() {
        return tslot;
    }

    /**
     * Sets the value of the tslot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTslot(String value) {
        this.tslot = value;
    }

    /**
     * Gets the value of the tslotLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTslotLevel() {
        if (tslotLevel == null) {
            return  0;
        } else {
            return tslotLevel;
        }
    }

    /**
     * Sets the value of the tslotLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTslotLevel(Integer value) {
        this.tslotLevel = value;
    }

    /**
     * Gets the value of the dispelCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispelCategory() {
        if (dispelCategory == null) {
            return "NONE";
        } else {
            return dispelCategory;
        }
    }

    /**
     * Sets the value of the dispelCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispelCategory(String value) {
        this.dispelCategory = value;
    }

    /**
     * Gets the value of the reqDispelLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReqDispelLevel() {
        return reqDispelLevel;
    }

    /**
     * Sets the value of the reqDispelLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReqDispelLevel(Integer value) {
        this.reqDispelLevel = value;
    }

    /**
     * Gets the value of the activation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivation() {
        return activation;
    }

    /**
     * Sets the value of the activation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivation(String value) {
        this.activation = value;
    }

    /**
     * Gets the value of the stigma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStigma() {
        return stigma;
    }

    /**
     * Sets the value of the stigma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStigma(String value) {
        this.stigma = value;
    }

    /**
     * Gets the value of the ammospeed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAmmospeed() {
        return ammospeed;
    }

    /**
     * Sets the value of the ammospeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAmmospeed(Integer value) {
        this.ammospeed = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public int getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(int value) {
        this.duration = value;
    }

    /**
     * Gets the value of the cooldown property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCooldown() {
        if (cooldown == null) {
            return  0;
        } else {
            return cooldown;
        }
    }

    /**
     * Sets the value of the cooldown property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCooldown(Integer value) {
        this.cooldown = value;
    }

    /**
     * Gets the value of the pvpDamage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPvpDamage() {
        return pvpDamage;
    }

    /**
     * Sets the value of the pvpDamage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPvpDamage(Integer value) {
        this.pvpDamage = value;
    }

    /**
     * Gets the value of the pvpDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPvpDuration() {
        return pvpDuration;
    }

    /**
     * Sets the value of the pvpDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPvpDuration(Integer value) {
        this.pvpDuration = value;
    }

    /**
     * Gets the value of the chainSkillProb property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getChainSkillProb() {
        if (chainSkillProb == null) {
            return  0;
        } else {
            return chainSkillProb;
        }
    }

    /**
     * Sets the value of the chainSkillProb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setChainSkillProb(Integer value) {
        this.chainSkillProb = value;
    }

    /**
     * Gets the value of the cancelRate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCancelRate() {
        if (cancelRate == null) {
            return  0;
        } else {
            return cancelRate;
        }
    }

    /**
     * Sets the value of the cancelRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCancelRate(Integer value) {
        this.cancelRate = value;
    }

    /**
     * Gets the value of the stance property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getStance() {
        if (stance == null) {
            return false;
        } else {
            return stance;
        }
    }

    /**
     * Sets the value of the stance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStance(Boolean value) {
        this.stance = value;
    }

    /**
     * Gets the value of the skillsetException property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSkillsetException() {
        if (skillsetException == null) {
            return  0;
        } else {
            return skillsetException;
        }
    }

    /**
     * Sets the value of the skillsetException property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSkillsetException(Integer value) {
        this.skillsetException = value;
    }

    /**
     * Gets the value of the skillsetMaxoccur property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSkillsetMaxoccur() {
        if (skillsetMaxoccur == null) {
            return  0;
        } else {
            return skillsetMaxoccur;
        }
    }

    /**
     * Sets the value of the skillsetMaxoccur property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSkillsetMaxoccur(Integer value) {
        this.skillsetMaxoccur = value;
    }

    /**
     * Gets the value of the avatar property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getAvatar() {
        if (avatar == null) {
            return false;
        } else {
            return avatar;
        }
    }

    /**
     * Sets the value of the avatar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAvatar(Boolean value) {
        this.avatar = value;
    }

    /**
     * Gets the value of the ground property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getGround() {
        if (ground == null) {
            return false;
        } else {
            return ground;
        }
    }

    /**
     * Sets the value of the ground property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGround(Boolean value) {
        this.ground = value;
    }

    /**
     * Gets the value of the unpottable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getUnpottable() {
        if (unpottable == null) {
            return false;
        } else {
            return unpottable;
        }
    }

    /**
     * Sets the value of the unpottable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnpottable(Boolean value) {
        this.unpottable = value;
    }

    /**
     * Gets the value of the removeFlyend property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getRemoveFlyend() {
        return removeFlyend;
    }

    /**
     * Sets the value of the removeFlyend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRemoveFlyend(Boolean value) {
        this.removeFlyend = value;
    }

    /**
     * Gets the value of the noremoveatdie property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getNoremoveatdie() {
        return noremoveatdie;
    }

    /**
     * Sets the value of the noremoveatdie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoremoveatdie(Boolean value) {
        this.noremoveatdie = value;
    }

}
