//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SkillElement.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SkillElement">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FIRE"/>
 *     &lt;enumeration value="WIND"/>
 *     &lt;enumeration value="WATER"/>
 *     &lt;enumeration value="EARTH"/>
 *     &lt;enumeration value="DARK"/>
 *     &lt;enumeration value="LIGHT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SkillElement")
@XmlEnum
public enum SkillElement {

    FIRE,
    WIND,
    WATER,
    EARTH,
    DARK,
    LIGHT;

    public String value() {
        return name();
    }

    public static SkillElement fromValue(String v) {
        return valueOf(v);
    }

}
