//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpellAtkDrainInstantEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpellAtkDrainInstantEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}DamageEffect">
 *       &lt;attribute name="hp_percent" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="mp_percent" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpellAtkDrainInstantEffect")
public class SpellAtkDrainInstantEffect
    extends DamageEffect
{

    @XmlAttribute(name = "hp_percent")
    protected Integer hpPercent;
    @XmlAttribute(name = "mp_percent")
    protected Integer mpPercent;

    /**
     * Gets the value of the hpPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHpPercent() {
        return hpPercent;
    }

    /**
     * Sets the value of the hpPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHpPercent(Integer value) {
        this.hpPercent = value;
    }

    /**
     * Gets the value of the mpPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMpPercent() {
        return mpPercent;
    }

    /**
     * Sets the value of the mpPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMpPercent(Integer value) {
        this.mpPercent = value;
    }

}
