//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SummonHomingEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SummonHomingEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}SummonEffect">
 *       &lt;attribute name="npc_count" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="attack_count" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SummonHomingEffect")
public class SummonHomingEffect
    extends SummonEffect
{

    @XmlAttribute(name = "npc_count")
    protected Integer npcCount;
    @XmlAttribute(name = "attack_count")
    protected Integer attackCount;

    /**
     * Gets the value of the npcCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNpcCount() {
        return npcCount;
    }

    /**
     * Sets the value of the npcCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNpcCount(Integer value) {
        this.npcCount = value;
    }

    /**
     * Gets the value of the attackCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAttackCount() {
        return attackCount;
    }

    /**
     * Sets the value of the attackCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAttackCount(Integer value) {
        this.attackCount = value;
    }

}
