//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ToyPetAdoptAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ToyPetAdoptAction">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractItemAction">
 *       &lt;attribute name="petid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="minutes" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="sidekick" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ToyPetAdoptAction")
public class ToyPetAdoptAction
    extends AbstractItemAction
{

    @XmlAttribute
    protected Integer petid;
    @XmlAttribute
    protected Integer minutes;
    @XmlAttribute
    protected Boolean sidekick;

    /**
     * Gets the value of the petid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPetid() {
        return petid;
    }

    /**
     * Sets the value of the petid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPetid(Integer value) {
        this.petid = value;
    }

    /**
     * Gets the value of the minutes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinutes() {
        return minutes;
    }

    /**
     * Sets the value of the minutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinutes(Integer value) {
        this.minutes = value;
    }

    /**
     * Gets the value of the sidekick property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getSidekick() {
        return sidekick;
    }

    /**
     * Sets the value of the sidekick property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSidekick(Boolean value) {
        this.sidekick = value;
    }

}
