//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UseLimits complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UseLimits">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ownership_world" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="usearea" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rank_max" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="rank_min" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="gender" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="usedelayid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="usedelay" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="usable_ride" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UseLimits")
public class UseLimits {

    @XmlAttribute(name = "ownership_world")
    protected Integer ownershipWorld;
    @XmlAttribute
    protected String usearea;
    @XmlAttribute(name = "rank_max")
    protected Integer rankMax;
    @XmlAttribute(name = "rank_min")
    protected Integer rankMin;
    @XmlAttribute
    protected String gender;
    @XmlAttribute
    protected Integer usedelayid;
    @XmlAttribute
    protected Integer usedelay;
    @XmlAttribute(name = "usable_ride")
    protected Integer usableRide;

    /**
     * Gets the value of the ownershipWorld property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOwnershipWorld() {
        return ownershipWorld;
    }

    /**
     * Sets the value of the ownershipWorld property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOwnershipWorld(Integer value) {
        this.ownershipWorld = value;
    }

    /**
     * Gets the value of the usearea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsearea() {
        return usearea;
    }

    /**
     * Sets the value of the usearea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsearea(String value) {
        this.usearea = value;
    }

    /**
     * Gets the value of the rankMax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRankMax() {
        return rankMax;
    }

    /**
     * Sets the value of the rankMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRankMax(Integer value) {
        this.rankMax = value;
    }

    /**
     * Gets the value of the rankMin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRankMin() {
        return rankMin;
    }

    /**
     * Sets the value of the rankMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRankMin(Integer value) {
        this.rankMin = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the usedelayid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUsedelayid() {
        return usedelayid;
    }

    /**
     * Sets the value of the usedelayid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUsedelayid(Integer value) {
        this.usedelayid = value;
    }

    /**
     * Gets the value of the usedelay property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUsedelay() {
        return usedelay;
    }

    /**
     * Sets the value of the usedelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUsedelay(Integer value) {
        this.usedelay = value;
    }

    /**
     * Gets the value of the usableRide property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUsableRide() {
        return usableRide;
    }

    /**
     * Sets the value of the usableRide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUsableRide(Integer value) {
        this.usableRide = value;
    }

}
