//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.23 at 01:29:26 PM CET 
//


package com.parser.output.aion.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WeaponStats complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeaponStats">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="min_damage" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="max_damage" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="attack_speed" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="physical_critical" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="physical_accuracy" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="parry" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="magical_accuracy" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="boost_magical_skill" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="attack_range" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="hit_count" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="reduce_max" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeaponStats")
public class WeaponStats {

    @XmlAttribute(name = "min_damage")
    protected Integer minDamage;
    @XmlAttribute(name = "max_damage")
    protected Integer maxDamage;
    @XmlAttribute(name = "attack_speed")
    protected Integer attackSpeed;
    @XmlAttribute(name = "physical_critical")
    protected Integer physicalCritical;
    @XmlAttribute(name = "physical_accuracy")
    protected Integer physicalAccuracy;
    @XmlAttribute
    protected Integer parry;
    @XmlAttribute(name = "magical_accuracy")
    protected Integer magicalAccuracy;
    @XmlAttribute(name = "boost_magical_skill")
    protected Integer boostMagicalSkill;
    @XmlAttribute(name = "attack_range")
    protected Integer attackRange;
    @XmlAttribute(name = "hit_count")
    protected Integer hitCount;
    @XmlAttribute(name = "reduce_max")
    protected Integer reduceMax;

    /**
     * Gets the value of the minDamage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinDamage() {
        return minDamage;
    }

    /**
     * Sets the value of the minDamage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinDamage(Integer value) {
        this.minDamage = value;
    }

    /**
     * Gets the value of the maxDamage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxDamage() {
        return maxDamage;
    }

    /**
     * Sets the value of the maxDamage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxDamage(Integer value) {
        this.maxDamage = value;
    }

    /**
     * Gets the value of the attackSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAttackSpeed() {
        return attackSpeed;
    }

    /**
     * Sets the value of the attackSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAttackSpeed(Integer value) {
        this.attackSpeed = value;
    }

    /**
     * Gets the value of the physicalCritical property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPhysicalCritical() {
        return physicalCritical;
    }

    /**
     * Sets the value of the physicalCritical property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPhysicalCritical(Integer value) {
        this.physicalCritical = value;
    }

    /**
     * Gets the value of the physicalAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPhysicalAccuracy() {
        return physicalAccuracy;
    }

    /**
     * Sets the value of the physicalAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPhysicalAccuracy(Integer value) {
        this.physicalAccuracy = value;
    }

    /**
     * Gets the value of the parry property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getParry() {
        return parry;
    }

    /**
     * Sets the value of the parry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setParry(Integer value) {
        this.parry = value;
    }

    /**
     * Gets the value of the magicalAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMagicalAccuracy() {
        return magicalAccuracy;
    }

    /**
     * Sets the value of the magicalAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMagicalAccuracy(Integer value) {
        this.magicalAccuracy = value;
    }

    /**
     * Gets the value of the boostMagicalSkill property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBoostMagicalSkill() {
        return boostMagicalSkill;
    }

    /**
     * Sets the value of the boostMagicalSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBoostMagicalSkill(Integer value) {
        this.boostMagicalSkill = value;
    }

    /**
     * Gets the value of the attackRange property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAttackRange() {
        return attackRange;
    }

    /**
     * Sets the value of the attackRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAttackRange(Integer value) {
        this.attackRange = value;
    }

    /**
     * Gets the value of the hitCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHitCount() {
        return hitCount;
    }

    /**
     * Sets the value of the hitCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHitCount(Integer value) {
        this.hitCount = value;
    }

    /**
     * Gets the value of the reduceMax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReduceMax() {
        return reduceMax;
    }

    /**
     * Sets the value of the reduceMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReduceMax(Integer value) {
        this.reduceMax = value;
    }

}
